### ISSUE TITLE
reqCookie support in AccessLog pattern?

### ISSUE THREAD

**Issue by psu1025** [logstash/logstash-logback-encoder#113]
Hello.

I'm use LogstashAccessTcpSocketAppender and AccessEventCompositeJsonEncoder with tomcat7.

I had trouble.
My encoder pattern so log and used many requestAttribute parameter.
Then, my spring application put "spring security unauthenticated error".
And i tried delete some attribute, Application was working well.

And find this document.
I think this is the cause of the problem.

"Note that the latest Logback (1.1.2 at the moment of writing), does not support deferred processing of request attributes. And because LogstashAccessTcpSocketAppender defers processing of the event to a background thread, you won't be able to use "%requestAttribute{name}" with TCP appender until this issue is fixed (or you build yourself a custom logback). http://jira.qos.ch/browse/LOGBACK-1033"

But now, logback is version up and that issue is fixed. (i use 1.1.3)

requestAttribute support logstash-logback-encoder-4.4?

If does not support, Can i avoid this problem use lower version? (logback, logstash-logback-encoder)

Thanks.

**Comment by philsttr** [comment]
Hi @psu1025 ,

Can you provide the full stacktrace of the error you are receiving?

Can you provide your logback.xml configuration?

I have not tested logging request attributes via `LogstashAccessTcpSocketAppender` when using logstash logback encoder 4.4 and logback 1.1.3.  Theoretically it should work though.

**Comment by psu1025** [comment]
Thanks your reply @philsttr ,

First, sorry. 
I'm try some process for provide full stacktrace.
In place of, this is part of  error message.

__spring_security_scpf_applied : true#NL#autoLoginAuthenticationFilter.FILTERED : true#NL#org.springframework.security.web.FilterChainProxy.APPLIED : true#NL#helpPageFilter.FILTERED : true#NL#__spring_security_session_mgmt_filter_applied : true#NL#__spring_security_filterSecurityInterceptor_filterApplied : true#NL#(inner bean)#2f0abf40.FILTERED : true#NL#org.springframework.web.context.request.RequestContextListener.REQUEST_ATTRIBUTES : org.apache.catalina.connector.Request@6c344838#NL#COOKIE_OBJECT : {SID=72dd14e27d96dc61a8a0f20053819e81, BID=02478906b6413766ceec2554ac6201e8, AID=c2dee9af-c474-4ead-b8f0-7596397d4d39}#NL#org.springframework.web.context.request.async.WebAsyncManager.WEB_ASYNC_MANAGER : org.springframework.web.context.request.async.WebAsyncManager


Second, This is my logback-access.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <appender name="stash" class="net.logstash.logback.appender.LogstashAccessTcpSocketAppender">
        <!-- remoteHost and port are optional (default values shown) -->
        <remoteHost>127.0.0.1</remoteHost>
        <port>4560</port>

        <!-- encoder is required -->
        <encoder class="net.logstash.logback.encoder.AccessEventCompositeJsonEncoder">
            <providers>
                <pattern>
                    <pattern>
                        {
                        "Date":"[%t]",
                        "URL":"%U",
                        "Status":"%s",
                        "ResponseTime":"%D",
                        "BytesSent":"%bytesSent",
                        "UploadSize":"%reqAttribute{uploadSize}",
                        "UserAgent":"%i{User-Agent}",
                        "UserID":"%reqAttribute{userId}",
                        "RequestID":"%reqAttribute{requestId}",
                        "RemoteID":"%a",
                        "PCAInfo":"%i{x-infraware-pca-info}",
                        "paramSegement":"%reqAttribute{paramSegments}",
                        "ForwardIP":"%i{x-forwarded-for}",
                        "Platform":"%reqAttribute{platform}",
                        "AID":"%reqCookie{AID}",
                        "BID":"%reqCookie{BID}",
                        "SID":"%reqCookie{SID}",
                        "disconnect":"%reqAttribute{disconnect}",
                        "PushID":"%reqAttribute{var1}",
                        "app":"%reqAttribute{app}",
                        "extra":"%reqAttribute{extra}",
                        "parameter":"%reqAttribute{parameterLog}"
                        }
                    </pattern>
                </pattern>
            </providers>
        </encoder>
    </appender>

    <appender-ref ref="stash" />
</configuration>
```

**Comment by psu1025** [comment]
I find some information.

http://jira.qos.ch/browse/LOGBACK-1033
That issue fixed in this link.
https://github.com/qos-ch/logback/commit/5909fcbb86702f4086131ba15cafec11efda51c4
copyAttributeMap function is core.
That function contain prepareForDeferredProcessing function.
logback's default appender, logstash-logback-encoder's another appender call that function.

But LogstashAccessTcpSocketAppender is do not call that function.
LogstashTcpSocketAppender is call super's prepareForDeferredProcessing.
(LogstashAccessTcpSocketAppender and LogstashTcpSocketAppender extends same class)
(I don't know that implementation is correct. I find logback's appender, this is sample.)
```
protected void postProcessEvent(IAccessEvent event) {
    event.prepareForDeferredProcessing();
  }
```

**Comment by philsttr** [comment]
`IAccessEvent.prepareForDeferredProcessing` is called from `AsyncDisruptorAppender.prepareForDeferredProcessing` [here](https://github.com/logstash/logstash-logback-encoder/blob/master/src/main/java/net/logstash/logback/appender/AsyncDisruptorAppender.java#L425)

`LogstashAccessTcpSocketAppender` does not override `AsyncDisruptorAppender.prepareForDeferredProcessing`.  Therefore, the implementation from `AsyncDisruptorAppender.prepareForDeferredProcessing` _will_ execute.

So, I don't see a problem there.


I noticed that your configuration that breaks includes `%reqCookie`.  And your configuration that works does not include `%reqCookie`.

And since the error message you are receiving mentions cookies, that leads me to believe that the cookie access is causing the problem.

Can you try removing everything except the `%reqCookie` fields, and see if that works?

Then try adding a `%reqCookie` field, and see if that breaks.

**Comment by psu1025** [comment]
@philsttr , you are right.

I try removing every %reqCookie, that works fine.
But add %reqCookie, error occurred. (just one reqCookie, error occurred)

**Comment by philsttr** [comment]
Logback's `AccessEvent` does not support asynchronous logging of request cookies.

Since `LogstashAccessTcpAppender` is an asynchronous appender, it is currently impossible to log request cookies using the `LogstashAccessTcpAppender`.


In order for logback to support it, [`AccessEvent.prepareForDeferredProcessing`](https://github.com/qos-ch/logback/blob/5a85af990c8f9f2e87699ace8610f6e10ecc447e/logback-access/src/main/java/ch/qos/logback/access/spi/AccessEvent.java#L532) would need to copy the cookies into a local map, similar to how it does for attributes (see [`AccessEvent.copyAttributeMap`](https://github.com/qos-ch/logback/blob/5a85af990c8f9f2e87699ace8610f6e10ecc447e/logback-access/src/main/java/ch/qos/logback/access/spi/AccessEvent.java#L326) and [`AccessEvent.getAttribute`](https://github.com/qos-ch/logback/blob/5a85af990c8f9f2e87699ace8610f6e10ecc447e/logback-access/src/main/java/ch/qos/logback/access/spi/AccessEvent.java#L313))


To fix this problem, you can open an issue with logback, or submit a PR to logback.

I'm going to close this issue for now.  Unfortunately, nothing can be done in logstash-logback-encoder to fix this.
