### ISSUE TITLE
TCPSocketAppender with failover

### ISSUE THREAD

**Issue by brenuart** [logstash/logstash-logback-encoder#115]
I'm looking for a way to add some failover behaviour to the `LogstashTCPSocketAppender` such that it would temporarily connect to a secondary server when the primary is not reachable. When connected to the secondary, the appender would retry on the master at regular interval until it succeeds.

We are running multiple services per host in a container environment. A log collector is running on every host - services are configured to send their log to the local log collector. If not available, then they should connect to another whose only purpose is to serve as fallback when one of the primaries fail. This setup allows us to shutdown temporarily the local log collector for maintenance without affecting the log collection.

As far as I can't tell such feature is not supported out-of-the box by the `LogstashTCPSocketAppender`. We had a look at the current implementation to see if we could somehow customise it to match our needs but unfortunately most of the relevant classes are either private or package protected. 

We were wondering if such feature is of interest to other people and if you have plans to implement it soon or later.

**Comment by philsttr** [comment]
Hi @brenuart ,

Have you considered using a VIP/load balancer?  I ask, because I have most often seen this use case (not just for logging, but any TCP service) handled on the destination side, without complex logic being required of clients.

**Comment by brenuart** [comment]
Yes of course but we are in a situation where customer don't want to hear about such solution :-(
Stupid, 'cause a simple HAProxy could do the job. So we currently have no other choice than a software solution inside the logging client.

**Comment by philsttr** [comment]
Ok.  Understood.

I'm somewhat hesitant to add this functionality to logstash-logback-encoder, since it is not the best practice to do this within a client side library.  

However, please feel free to submit a PR, and I'll take a look.  If it's not terribly complex, I'll merge it.

I'm thinking it could be as simple as changing `AbstractLogstashTcpSocketAppender.TcpSendingEventHandler.openSocket()` to go down a list of `remoteHost` names as it loops, rather than a single remoteHost.  It would connect to the first one that accepts the connection.

Then, you can control the behavior on the server side by:
* bring up secondary host
* take down primary host
* appender will reconnect to secondary
* perform maintenance on primary
* bring up primary host
* take down secondary host
* appender will reconnect to primary

**Comment by brenuart** [comment]
Since `TcpSendingEventHandler` is a private inner class, I was currently playing at the `SocketFactory` level. It is a big ugly I admit, but that's the only solution I found so far.

The behaviour is somewhat similar to what you described except that the appender will try to reconnect to the primary host at regular interval. The idea is every client should stick to its assigned primary unless it is not available. So, when connected to another host than the primary, my implementation closed the socket after a while to force a reconnect attempt to the primary.

I'll try to apply those changes to `TcpSendingEventHandler` and send a PR as soon as I can.

**Comment by philsttr** [comment]
Honestly, I'd rather it not ping the primary when it's connected to a secondary, since that is 'yet another scheduled task' that needs to be managed.

You can easily trigger the fail-back-to-primary event on the server side, by closing all the existing connections on the secondary.  This will force the reconnect logic on the client to go through its list of addresses again, and it'll connect to primary first.

This will simplify the client-side logic a lot.

**Comment by brenuart** [comment]
That's exactly what I'm doing: forcibly close connections to the secondary after a while to force a reconnect attempt to the primary. No housekeeping thread... (see my previous comment).

As described, I'm currently pushing that behaviour in the current code base by hacking/proxying the SocketFactory... which is far from being easy :( 
Maybe I should directly fork the project and submit a PR for you to have a look. But I'm a bit worried if the feature is not merged at the end... 'cause we need the functionality.

**Comment by philsttr** [comment]
Released in 4.5

**Comment by brenuart** [comment]
Cool. Thanks for the work!

**Comment by Fr33Radical** [comment]
Hello, I saw the pull request, but would it be possible to have some documentation on how to use it or a xml configuration file as an example on how to use it?

Thanks!
