### ISSUE TITLE
Old format layouts

### ISSUE THREAD

**Issue by juise** [logstash/logstash-logback-encoder#131]
For some reason I need to keep save the backward compatibility, how can I produce logs in JSONEventLayoutV0 and JSONEventLayoutV1 formats?

**Comment by philsttr** [comment]
Hi @juise ,

You can customize the field names as needed to get the format that you would like.

See [here](https://github.com/logstash/logstash-logback-encoder#custom_field_names) for how to customize the field names for LogstashEncoder.

If you're using the [composite encoder](https://github.com/logstash/logstash-logback-encoder#composite_encoder), then the field names can be specified on each provider.

**Comment by juise** [comment]
I've already looked at composite encoder and I can't make what I need. I need to make it from code directly! How can I make something like:

```
{"@fields":{"level":"INFO","threadName":"clojure-agent-send-off-pool-1","mdc":{},"file":"logging.clj","class":"clojure.tools.logging$eval513$fn__519","line_number":"288","method":"invoke","loggerName":"riemann.transport.websockets"},"@timestamp":"2015-08-25T18:34:22.954Z","@message":"Websockets server 127.0.0.1 5556 online","@source_host":"ip-172-31-31-101"}
```

**Comment by philsttr** [comment]
Hi @juise,

Unfortunately, due to the nested `@fields` node, the only way to produce that output would be to write your own `JsonProvider`, and use it with the `CompositeJsonEncoder`.


I tried using the `LoggingEventPatternJsonProvider` to produce this output using the below configuration, but unfortunately, I ran into two problems:

1. the mdc can't be added in the nested field like that
2. [LOGBACK-1101](http://jira.qos.ch/browse/LOGBACK-1101) prevents logback from properly passing the string to the provider

```xml
        <!-- this does not work -->
        <encoder class="net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder">
            <providers>
                <pattern>
                    <pattern>{"@timestamp":"%date","@fields":{"level":"%level","threadName":"%thread","file":"%file","class":"%class","line_number":"#asLong{%line}","method":"%method","loggerName":"%logger"},"@message":"%message"}
                    </pattern>
                </pattern>
            </providers>
        </encoder>
```

If you do end up writing a `JsonProvider`, feel free to submit a pull request for consideration on including in logstash-logback-encoder.  I would suggest implementing a `NestedFieldJsonProvider` that would write the nested field, and then delegate to other `JsonProviders`.  This would be a reusable provider, that you could configure it like this:

```xml
<encoder class="net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder">
    <providers>
        <timestamp>
            <fieldName>@timestamp</fieldName>
        </timestamp>
        <message>
            <fieldName>@message</fieldName>
        </message>
        <globalCustomFields>
            <customFields>{"@source_host":"${HOSTNAME}"}</customFields>
        </globalCustomFields>
        <nestedField>
            <fieldName>@fields</fieldName>
            <providers>
                <logLevel/>
                <loggerName>
                    <fieldName>loggerName</fieldName>
                </loggerName>
                <threadName>
                    <fieldName>thread</fieldName>
                </threadName>
                <callerData>
                    <classFieldName>class</classFieldName>
                    <methodFieldName>method</methodFieldName>
                    <fileFieldName>file</fileFieldName>
                    <lineFieldName>line_number</lineFieldName>
                </callerData>
                <mdc>
                    <fieldName>mdc</fieldName>
                </mdc>
                <stackTrace/>
            </providers>
        <nestedField>
    </providers>
</encoder>
```

**Comment by juise** [comment]
@philsttr I stumble upon the same problems, so I decide to fork [log4j-jsonevent-layout](https://github.com/logstash/log4j-jsonevent-layout) and rewrite it with logback support [logstash-logback-layout](https://github.com/juise/logstash-logback-layout). I think I can try make the same based on NestedFieldJsonProvider as you suggested!

How do you think, if I transform the follow xml config to the java code, the problem disappear?
``` xml
       <!-- this does not work -->
        <encoder class="net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder">
            <providers>
                <pattern>
                    <pattern>{"@timestamp":"%date","@fields":{"level":"%level","threadName":"%thread","file":"%file","class":"%class","line_number":"#asLong{%line}","method":"%method","loggerName":"%logger"},"@message":"%message"}
                    </pattern>
                </pattern>
            </providers>
        </encoder>
```

Thanks a lot for the help!

**Comment by philsttr** [comment]
Yes.  I think if you programmatically configure logback with java, rather than relying on xml configuration, it _should_ work, since you will bypass logback's property resolution.  I haven't tried it though.  If you try it, let me know how it goes.

Also note, that the MDC is not in the pattern, so you won't be able to get MDC values generically.  However, If you have specific MDC keys that you care about, you could get them by adding `%mdc{key}` to the pattern somewhere.

**Comment by philsttr** [comment]
Hey @juise,

I've added a nested object provider, so the logstash v0 format is now possible to create using the composite encoders.  See [here](https://github.com/logstash/logstash-logback-encoder#provider_nested)

**Comment by philsttr** [comment]
This will be available when 4.6 is released.

**Comment by juise** [comment]
Terrific, thanks! It's very helpful for me!

**Comment by philsttr** [comment]
4.6 has been released and is on its way to maven central

**Comment by juise** [comment]
Thanks!
