### ISSUE TITLE
 logback-encoder enable ESCAPE_NON_ASCII 

### ISSUE THREAD

**Issue by wyzssw** [logstash/logstash-logback-encoder#143]
```
private MappingJsonFactory jsonFactory = (MappingJsonFactory) new MappingJsonFactory()
        .enable(JsonGenerator.Feature.ESCAPE_NON_ASCII)
```

the log print 
```
"\u95E8\u5E97\u4E0D\u5B58\u5728\"
```
what the advantage for  logback-encoder  do this

**Comment by philsttr** [comment]
I'm not entirely sure.  It has been that way since this library was created by @neilprosser .  Neil, do you have any input here?

If you don't want this behavior, you can do the following;

1. Create a `JsonGeneratorDecorator`...

```java
public class NonEscapingJsonGeneratorDecorator implements JsonGeneratorDecorator {

	@Override
	public JsonGenerator decorate(JsonGenerator generator) {
		return generator.disable(JsonGenerator.Feature.ESCAPE_NON_ASCII);
	}
}
```

2. [Configure the encoder to use your decorator](https://github.com/logstash/logstash-logback-encoder#custom_factory)...

```xml
<encoder class="net.logstash.logback.encoder.LogstashEncoder">
  <jsonGeneratorDecorator class="your.package.NonEscapingJsonGeneratorDecorator"/>
</encoder>
```

**Comment by wyzssw** [comment]
Thank you ,i will try

**Comment by neilprosser** [comment]
Hmm. I'm not too sure about that. It was a long time ago! I know that the JSON spec specifies that only unicode characters can be used, otherwise they need to be escaped so I'm hoping it was to ensure that we adhere to the spec, especially if it's strictly adhered to by the applications we end up sending the JSON to. We'll have to leave the default as it is but the method of switching the decorator as given is absolutely the right move.

**Comment by philsttr** [comment]
#261 will disable ESCAPE_NON_ASCII by default
