### ISSUE TITLE
LoggingEvent message vs. AccessEvent @message

### ISSUE THREAD

**Issue by jenshadlich** [logstash/logstash-logback-encoder#150]
I wonder why the field names differ. Is it purpose or mistake?

For me it's not convenient because it's easy to overlook and I log into the same backend.

What I did ist to adjust the field name with `AccessEventCompositeJsonEncoder`:

```
<providers>
    <accessMessage>
        <fieldName>message</fieldName>
    </accessMessage>
</providers>
```

Works, but I feel this shouldn't be necessary.

**Comment by philsttr** [comment]
Looking back through the commit history...

1. `LoggingEvent` originally used `@message`.  `LoggingEvent` was changed from `@message` to `message` in logstash-logback-encoder v2.0, presumably because logstash's format changed around that time.  At that time `AccessEvent` wasn't supported.
2. `AccessEvent` was introduced in v2.1 with the old `@message` format.

At this point, we can't change the field names without a major version bump.  #138 is also requesting some field name changes for access events (to remove the dots), so in 5.0 we can probably change the field names (while allowing an easy way to go back to the old field names)

**Comment by philsttr** [comment]
Field has been renamed from `@message` to `message` in 5.0 (not released yet)
