### ISSUE TITLE
Order of messages in logstash

### ISSUE THREAD

**Issue by sverin** [logstash/logstash-logback-encoder#164]
Our implementation of the logstash logback encoder send multiple messages to the server.
When they are sent frequently, i.e. in trace mode, we're having issues sorting them i Kibana.

Is there a way to see the exact order they have been sent? Or how can we sort to see the exact order?

Now, we receive multiple messages with the exact timestamp on millisecond.

**Comment by philsttr** [comment]
Which appender are you using?  The TCP appender or the UDP appender?

I ask, because ordering is not guaranteed with the UDP appender.

The TCP appender will send messages according to the order in which they are logged by the application.  If multiple events occur at the exact same time (by multiple threads), then the events will be sent in the order in which they are enqueued, which would be determined by the thread scheduler.

The only way to "sort" the messages is by the timestamp, which is stamped by logback, before the appenders in logstash-logback-encoder receive the event.

So, unfortunately, there's not really a built-in way to see the order in which they are sent on the application side.

For debugging purposes, you could setup logstash with one input, and two outputs (elasticsearch and a file).  Then you could look at the file to determine the order in which they were sent.
