### ISSUE TITLE
hostname and remoteHost both return `event.getRemoteHost()`

### ISSUE THREAD

**Issue by avdv** [logstash/logstash-logback-encoder#176]
What's the difference between the `fieldsHostname` and `fieldsRemoteHost` fields? Both return the same information which seems like a wasted effort or some bug lurking.

**Comment by philsttr** [comment]
Hmm.  Looks like it has been that way since support was first added for access events.  I'm not sure why.

[Here's the initial commit](https://github.com/logstash/logstash-logback-encoder/commit/0c67cff00bc0e9e03f566f53bfe55e11a60fea27#diff-ef3906cc887bb5e509073ab69138c76fR63) for support for access events.

It has since been separated out into separate providers, but the functionality remains the same.  I think the `fieldsHostname` should be removed, but I'd prefer to wait until a major release (e.g. 5.0) since this is a somewhat backwards incompatible change.

In the meantime, if you're using LogstashAccessEncoder/Layout, you can remove the fieldsHostname from being output like this:

```xml
<encoder class="net.logstash.logback.encoder.LogstashAccessEncoder">
  <fieldNames>
    <fieldsHostname>[ignore]</fieldsHostname>
  </fieldNames>
</encoder>
```

**Comment by philsttr** [comment]
hostname field has been removed in 5.0 (not released yet)
