### ISSUE TITLE
Write json request/response as string

### ISSUE THREAD

**Issue by raquibmahmood** [logstash/logstash-logback-encoder#182]
Hi,

I am writing json log of rest web service. Access logs are generating properly in tomcat. But for json request/response its putting \ as escape character. I know in jackson writeAsString will solve this. How can I do this in here?
I have already tried useDefaultPrettyPrinter().

Thanks,
Shoeb

**Comment by philsttr** [comment]
Can you provide your logback-access.xml file, an example request, and an example of the output from logstash-logback-encoder?

**Comment by raquibmahmood** [comment]
below is my logback-access.xml 
`<configuration>
   <appender name="FILE" class="ch.qos.logback.core.rolling.RollingFileAppender">
    <file>c:/app-logs/access_log.json</file>
    <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
      <fileNamePattern>c:/app-logs/access.%d{yyyy-MM-dd}.log.zip</fileNamePattern>
    </rollingPolicy>
    <encoder class="net.logstash.logback.encoder.AccessEventCompositeJsonEncoder">
		<jsonGeneratorDecorator class="net.logstash.logback.decorate.PrettyPrint" />		
  <providers>
    <pattern>
      <pattern>
        {
		"timestamp": "%date{ISO8601}",		
		"requestURL":"%r",
		"httpHeader":"%i",		
        "requestContent":"%requestContent",		
		"responseContent":"%responseContent"		
       }
      </pattern>
    </pattern>
  </providers>    
</encoder>
  </appender> 
  <appender-ref ref="FILE" />
</configuration>
`

[access_log.zip](https://github.com/logstash/logstash-logback-encoder/files/424480/access_log.zip)

Please check the attachement for generated log.

**Comment by philsttr** [comment]
Logback's [requestContent](https://github.com/qos-ch/logback/blob/master/logback-access/src/main/java/ch/qos/logback/access/pattern/RequestContentConverter.java) and [resposeContent](https://github.com/qos-ch/logback/blob/master/logback-access/src/main/java/ch/qos/logback/access/pattern/ResponseContentConverter.java) just return the data as a string.

The AccessEventCompositeJsonEncoder doesn't know that the request/response are JSON, so it escapes the quotes in the string so that the event generated is valid JSON.

If I understand correctly, you want the requestContent and responseContent to be embedded in the log event as JSON objects, rather than escaped strings, like this:

```
{
  "timestamp" : "2016-08-18 03:59:13,101",
  "requestContent" : null,
  "responseContent" : [{"createUser":"API", ...
```


To do so, you will need to create your own JsonProvider.  Probably something like this:

```java
public class RequestContentJsonProvider extends AbstractFieldJsonProvider<IAccessEvent>{

    public RequestedUriJsonProvider() {
        setFieldName("requestContent");
    }
    
    @Override
    public void writeTo(JsonGenerator generator, IAccessEvent event) throws IOException {
        generator.writeFieldName(getFieldName());
        if (event.getRequestContent() == null || event.getRequestContent().isEmpty()) {
            generator.writeNull();
        } else {
            generator.writeRawValue(event.getRequestContent());
        }
    }
}
```

You can then configure it in your logback-access.xml like this:

```xml
<encoder class="net.logstash.logback.encoder.AccessEventCompositeJsonEncoder">
  <providers>
    <pattern>
      <pattern>
        {
        "timestamp": "%date{ISO8601}",      
        "requestURL":"%r",
        "httpHeader":"%i"
       }
      </pattern>
    </pattern>
    <provider class="RequestContentJsonProvider"/>
    <provider class="ResponseContentJsonProvider"/>
  </providers>    
</encoder>
```
