### ISSUE TITLE
end prefix with a space

### ISSUE THREAD

**Issue by cscetbon** [logstash/logstash-logback-encoder#186]
Hey guys,

whenever I add a space at the end of my pattern it's not respected. I tried to use `xml:space="preserve"` but it doesn't work.

I'd like to get something like 

```
<14> 2016-10-07T21:10:42.458Z log.json {"@timestamp":"2016-10-07T23:10:42.458+02:00"...
```

but I get 

```
<14> 2016-10-07T21:10:42.458Z log.json{"@timestamp":"2016-10-07T23:10:42.458+02:00"...
                                      ^
```

Here is the configuration I use : 

```
<appender name="loghost" class="net.logstash.logback.appender.LogstashTcpSocketAppender">
    <remoteHost>localhost</remoteHost>
    <encoder class="net.logstash.logback.encoder.LogstashEncoder">
      <prefix class="ch.qos.logback.core.encoder.LayoutWrappingEncoder">
          <layout class="ch.qos.logback.classic.PatternLayout">
            <pattern xml:space="preserve">&lt;14&gt; %date{"yyyy-MM-dd'T'HH:mm:ss.SSS", UTC}Z log.json </pattern>
          </layout>
      </prefix>
   </encoder>
  </appender>
```

Any idea how to fix it ? 

Thank you

**Comment by philsttr** [comment]
Hey @cscetbon ,

I _think_ this is caused by logback trimming whitespace before setting text values  (I haven't confirmed this by actually running your example though, so I could be wrong).  See [this code](https://github.com/qos-ch/logback/blob/c2dcbfcfb4048d11d7e81cd9220efbaaccf931fa/logback-core/src/main/java/ch/qos/logback/core/joran/event/BodyEvent.java#L27-L37)

If that is the case, I don't think there's anything that can be done in logstash-logback-encoder to prevent this.

The only solution I can think of (other than changing logback code), is to NOT use xml to configure logback, and instead configure it programmatically.  I realize that's a nasty workaround.

**Comment by cscetbon** [comment]
@philsttr unfortunately I can't use this nasty workaround (as you said). I'm trying to send logs written by Cassandra, and I don't want to patch C* to do it. 

Isn't there a way to add a separator between the prefix pattern and the json output ? 

If it's caused by the `trim()` function applied on my string, why adding `&#09;` at the end of my prefix doesn't work too ? is this character replaced by a certain number of spaces when read from the xml configuration file and then trimmed by the function ?

**Comment by philsttr** [comment]
I just tested this myself, and I can confirm that it is because of the [trim() in logback that I linked earlier](https://github.com/qos-ch/logback/blob/c2dcbfcfb4048d11d7e81cd9220efbaaccf931fa/logback-core/src/main/java/ch/qos/logback/core/joran/event/BodyEvent.java#L27-L37).

I tried with `&#09;` in the string, but unfortunately the xml parser converts it to a tab character before calling into logback.  So, `trim()` will remove that character as well, since it is just whitespace.

Here's another potential workaround.  Unfortunately, you'd have to write some code, and include it in cassandra's classpath.  You could create a custom `JsonGeneratorDecorator` that returns a custom `JsonGenerator` that inserts a string before writing anything else.

For example:

```java
public class WhitespacePrefixJsonGeneratorDecorator implements JsonGeneratorDecorator {
    @Override
    public JsonGenerator decorate(JsonGenerator generator) {
        return new WhitespacePrefixJsonGenerator(generator);
    }
    
    private static class WhitespacePrefixJsonGenerator extends JsonGeneratorDelegate {

        public WhitespacePrefixJsonGenerator(JsonGenerator delegate) {
            super(delegate);
            try {
                delegate.writeRaw(" ");
            } catch (IOException e) {
                throw new RuntimeException("Exception occurred while writing log prefix.", e);
            }
        }
    }
}
```

And then configure your encoder to use it:

```
<encoder class="net.logstash.logback.encoder.LogstashEncoder">
    <prefix class="ch.qos.logback.core.encoder.LayoutWrappingEncoder">
        <layout class="ch.qos.logback.classic.PatternLayout">
            <pattern xml:space="preserve">&lt;14&gt; %date{"yyyy-MM-dd'T'HH:mm:ss.SSS", UTC}Z log.json</pattern>
        </layout>
    </prefix>            
    <jsonGeneratorDecorator class="WhitespacePrefixJsonGeneratorDecorator"/>
</encoder>

```

I know all of these are workarounds.  I think the proper solution is to get logback's configuration logic (joran) to support untrimmed xml element bodies.

**Comment by philsttr** [comment]
Ah hah!  I just found another hack/workaround that doesn't require any code.

Try this:

```
<pattern xml:space="preserve">&lt;14&gt; %date{"yyyy-MM-dd'T'HH:mm:ss.SSS", UTC}Z%1mdc{keyThatWillNeverExist}</pattern>
```

This tells logback to output the MDC value with the key named `keyThatWillNeverExist` (which obviously doesn't exist), and pad the value by 1.  This will always output one space.

**Comment by cscetbon** [comment]
Thank you so much @philsttr. [It works exactly like I wanted. I](https://thetomatos.com/wp-content/uploads/2016/10/sticky-note-good-job-clipart.jpg) was going to use your first method when I saw it but not having to compile anything is far better. I agree that we should have a way to add a space without using such hacky ways  ... FYI, I've also removed `xml:space="preserve"` which doesn't seem necessary
