### ISSUE TITLE
Let CompositeJsonEncoder work for shared OutputStreams

### ISSUE THREAD

**Issue by mkr** [logstash/logstash-logback-encoder#189]
Currently, for one Event CompositeJsonEncoder#doEncode uses multiple consecutive writes on the original OutputStream. This creates concurrency issues when the OutputStream is shared between different threads even when single writes to OutputStream itself are thread-safe. Our use case is an OutputStream shared by two Logback appenders. A solution could be to buffer the whole output and write once. Patch can be provided if you consider this behaviour worth having.

**Comment by philsttr** [comment]
Can you go into more details on your use case?  I'd like to understand it better.

Where are you streaming events (file, socket, console, etc?) 

Can you open multiple streams to the same destination?

It seems a little odd to me to have multiple threads write to a single OutputStream.  While it may be possible, that seems like it's asking for trouble (memory pressure, lock contention, etc)

**Comment by mkr** [comment]
We use two ConsoleAppenders with differently configured LogstashEncoders (mainly differing in their pattern layout). They are used by loggers concurrently.

**Comment by philsttr** [comment]
Closing this issue because in logback version 1.2.0, the  `Encoder` interface was refactored such that it never directly references an `OutputStream`.  Instead, the `Encoder` now just returns a `byte[]`, and it is up to the appender to write the encoded value out to the `OutputStream`.  Therefore, the encoder cannot do anything to address this.

A fix could be made at the appender level, but the `ConsoleAppender` is a logback class, so the fix would need to be made in logback itself.

Having said that, I anticipate that since the entire encoded event is now being written to the `OutputStream` in one `write` call, you _might_ see less interleaving with logback 1.2.0+.

logstash-logback-encoder version 4.9 (not yet released) adds support for logback 1.2.0+.  So, give it a shot after 4.9 is released (or try 4.9-SNAPSHOT if you want to try early)
