### ISSUE TITLE
ConcurrentModificationException in AccessEvent.copyAttributeMap()

### ISSUE THREAD

**Issue by bedrin** [logstash/logstash-logback-encoder#191]
I saw following exception in my Tomcat log. Could have been caused by async request processing, although I'm not 100% sure. Anyway, it should be handled correctly.

> 14:51:16,240 |-ERROR in net.logstash.logback.appender.LogstashAccessTcpSocketAppender[AccessStash] - Appender [AccessStash] failed to append. java.util.ConcurrentModificationException
> 	at java.util.ConcurrentModificationException
> 	at 	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
> 	at 	at java.util.HashMap$KeyIterator.next(HashMap.java:1453)
> 	at 	at java.util.AbstractCollection.addAll(AbstractCollection.java:343)
> 	at 	at org.apache.catalina.connector.Request.getAttributeNames(Request.java:1032)
> 	at 	at ch.qos.logback.access.spi.AccessEvent.copyAttributeMap(AccessEvent.java:334)
> 	at 	at ch.qos.logback.access.spi.AccessEvent.prepareForDeferredProcessing(AccessEvent.java:553)
> 	at 	at net.logstash.logback.appender.AsyncDisruptorAppender.prepareForDeferredProcessing(AsyncDisruptorAppender.java:428)
> 	at 	at net.logstash.logback.appender.AsyncDisruptorAppender.append(AsyncDisruptorAppender.java:412)
> 	at 	at net.logstash.logback.appender.AsyncDisruptorAppender.append(AsyncDisruptorAppender.java:93)
> 	at 	at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:88)
> 	at 	at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:48)
> 	at 	at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:201)

**Comment by philsttr** [comment]
`AsyncDisruptorAppender` must call `event.prepareForDeferredProcessing()` to save the event state so that the event can be processed on another thread.

The question is what to do when `prepareForDeferredProcessing()` throws an exception.

The easiest option would be to catch any `Exception`, and ignore it.  This would result in incomplete information about the event being logged, since event state would not be captured completely before being dispatched to another thread.

A more specific (slightly better?) solution would be to handle `ConcurrentModificationException` by  calling `prepareForDeferredProcessing()` a few more times before giving up and continuing.  This would give a better chance of capturing _some_ event state.  However, the state captured would not represent the _exact_ state when the event occurred, since the state was modified by another thread before being completely captured.

So, I'll implement the more specific case, while also just ignoring other exceptions.

Any other suggestions on how you prefer to handle this are welcome.

**Comment by philsttr** [comment]
Starting in 5.0, events will be logged even if a `RuntimeException` (such as `ConcurrentModificationException`) occurs in `prepareForDeferredProcessing`
