### ISSUE TITLE
Cannot extend StructuredArguments class

### ISSUE THREAD

**Issue by huawangpp** [logstash/logstash-logback-encoder#204]
We want to extend StructuredArguments to add on our own strong typed custom key, for types like GeoPoint, Timestamp, etc. But StructuredArguments has private constructor, so we cannot extend the class. We can only create a new class. The integration is not as seamless. Can we allow extend StructuredArguments or is there any other suggestions?

**Comment by philsttr** [comment]
`StructuredArguments` only offers static factory methods.  It's common practice for classes that only provide static factory methods to not allow subclassing.  For example, see `java.util.concurrent.Executors` and `java.util.Objects` from java, or `com.google.common.base.MoreObjects` and `com.google.common.base.Functions` from guava, or many other examples.

There's not really much benefit to extending it, since it's not meant to be instantiated.

The only _minor_ benefit I can see is that your code would only need to static import your custom class, (instead of both `StructuredArguments` and your custom class) to get access to all the factory methods.   The code you use when logging would be the same in either case.  And since IDEs manage imports these days, I don't see that as much of a problem.

So, I would just suggest creating your own class that provides static factory methods for your custom StructuredArgument classes, and just static import your custom class and/or StructuredArguments` depending on what your logging code requires.


Having said that, I am curious about your use case for having custom types as _keys_.  Keys will need to serialize to Strings, since keys can only be strings in JSON.  Is your use case just that you do not want to convert your custom types to strings when logging?  e.g. `logger.log("my message", kv(geoPoint.toString(), foo)`.

Note that if you want to add custom serialization of _values_  (not _keys_), then you can configure jackson with additional modules that provide serializers for those custom types.  See [this comment](https://github.com/logstash/logstash-logback-encoder/issues/145#issuecomment-173449795) for how to add an additional module to jackson.
