### ISSUE TITLE
LogstashEncoder not compatible with Logback 1.2.x

### ISSUE THREAD

**Issue by codahale** [logstash/logstash-logback-encoder#205]
Logback 1.2.0 made major changes to the `Encoder` interface — specifically, `Encoder` is now expected to return byte arrays instead of writing to an `OutputStream`.

**Comment by thelamon** [comment]
Hi, guys.

I fixed this issue in my fork (branch is named 'logback-1.2'). It works for me in production just now.
I could prepare pull request but i need some help with tests.

All tests that check actual appending/formatting work well. But reconnection tests fail(LogstashTcpSocketAppenderTest / 6 are failed). Also single test 'testNoImmediateFlush' fails (logback changed something with immediate flush, so test may be irrelevant actually).

Should i fix all tests?Or is it possible to create pull request with these failing tests and expect some help?

**Comment by philsttr** [comment]
Hey @thelamon ,

Go ahead and submit the PR.  If you get a chance to work on the tests, you can update the PR.  Otherwise, I'll work on the tests.

I was thinking about how to make logstash-logback-encoder compatible with both logback 1.1.x AND 1.2.x, but that might be pretty hard.  So, this will likely require a major version bump (5.0) to denote the incompatibility with logback 1.1.  I'm actually surprised that logback didn't bump to 2.0, since that's a pretty major backwards incompatibility on their part.

**Comment by thelamon** [comment]
It is possible to make code logback 1.1.X and 1.2.X compatible.
There are two possible ways.

1. `LogstashEncoder` could use composition over inheritance so it will require some reflection checks at start to choose right implementation. It will be two real implementations (like `CompositeJsonEncoder11` and `CompositeJsonEncoder12`) with different APIs (because of changes in logback-1.2 `Encoder` class), so `LogstashEncoder` needs some adapter .... ?
This way will hide all differences between logback-1.1 / logback-1.2 from end user.
2. More simple way: just create two parallel class hierarchies (logback-1.1 and logback-1.2 compatible).
End user will need to write `LogstashEncoder12` (instead of `LogstashEncoder`) in logback.xml when migrating to logback-1.2. It seems to be very simple to implement but requires changes in logging configuration for end users.

**Comment by philsttr** [comment]
Committed support for logback 1.2.0+, while remaining backwards compatible with logback 1.1.x.

Thanks for PR #206, @thelamon.  While I did not merge it directly, I did reference it.  When working on the backwards compatibility code, I found it was easier to start from scratch, since I had to put the 1.1.x compatible code back in.

This will be released soon as version 4.9.  I'd really appreciate if you could test version 4.9-SNAPSHOT before I release it (you'll have to build it yourself).

**Comment by Martin-Wegner** [comment]
@philsttr can you please publish the snapshot on Maven central?

**Comment by philsttr** [comment]
I'll get this released sometime in the next week.  I want to do some additional testing on it first.

I won't be publishing the -SNAPSHOT version.

**Comment by stefan-zh** [comment]
Looking forward to this getting released this week

**Comment by philsttr** [comment]
[4.9](https://github.com/logstash/logstash-logback-encoder/releases/tag/logstash-logback-encoder-4.9) released
