### ISSUE TITLE
HOSTNAME not being sent after upgrade to 4.9

### ISSUE THREAD

**Issue by walbag** [logstash/logstash-logback-encoder#216]
Was on version 4.5.1 and upgraded to 4.9 to work with logback upgrade to 1.2.3. Now the HOSTNAME field is not being included with log messages.

**Comment by philsttr** [comment]
I believe this is a just a side effect of [LOGBACK-1221](https://jira.qos.ch/browse/LOGBACK-1221)

logstash-logback-encoder never explicitly added the HOSTNAME field.  logstash-logback-encoder just copies all of the properties from logback's context into the JSON output.  (See [ContextJsonProvider](https://github.com/logstash/logstash-logback-encoder/blob/master/src/main/java/net/logstash/logback/composite/ContextJsonProvider.java)).

Prior to logback 1.1.10, logback added the HOSTNAME property by default to the context.  After logback 1.1.10, logback lazily calculates the HOSTNAME as an optimization.

Since logstash-logback-encoder never added the HOSTNAME explicitly, I don't think it makes sense to re-add it.  Instead, I would recommend either
A) Explicitly add a HOSTNAME [property with context scope to logback](https://logback.qos.ch/manual/configuration.html#definingProps)
OR
B) Explicitly add a HOSTNAME [global custom field](https://github.com/logstash/logstash-logback-encoder#loggingevent_custom_global).

**Comment by walbag** [comment]
Thank you for this response! I rolled back to the previous logback, but this will be useful when we do upgrade.

**Comment by rwalkerands** [comment]
I just came across this issue myself.

I think it would be good to update `README.md` to reflect this change in logback's behaviour. It currently says:

> By default, each property of Logback's Context (`ch.qos.logback.core.Context`), such as `HOSTNAME`, will appear as a field in the LoggingEvent.

... and that could be taken to read that you _will_ see `HOSTNAME` in the logs by default.

**Comment by philsttr** [comment]
@rwalkerands,   Great suggestion.  Done.

**Comment by deradam** [comment]
I just discovered this issue in my logs and checked the linked documentation how to resolve the issues. However, I am not able to fix that. Can you point out where to add the @{HOSTNAME} property/value in the logback.xml so that it will be working again?

**Comment by philsttr** [comment]
@deradam , you can use [global custom fields](https://github.com/logstash/logstash-logback-encoder#global-custom-fields) to add the hostname property to logging events...

```
<customFields>{"HOSTNAME":"${HOSTNAME}"}</customFields>
```

**Comment by deradam** [comment]
@philsttr thanks, works like a charm!

**Comment by yoorick** [comment]
@philsttr , strangely enough, but the approach with `customFields` results in two identical `HOSTNAME` fields for each line in JSON log. While the approach with context-scoped property works correctly and produces only one `HOSTNAME` field.

```
<property scope="context" name="HOSTNAME" value="${HOSTNAME}" />
```
(I'm using logstash-logback-encoder 4.11 and logback-classic 1.2.3, if that matters.)
