### ISSUE TITLE
Data held in TCP BufferedOutputStream is lost when connection is dropped

### ISSUE THREAD

**Issue by brenuart** [logstash/logstash-logback-encoder#218]
The `TcpSendingEventHandler` puts a `BufferedOutputStream` around the TCP connection whose size is set to `8192` bytes by default. Consequence is up to 8192 bytes are lost when the connection is closed (not taking into account _inflight_ data that may sit in tcp buffers).

This is rather annoying, certainly for applications that generate a large amount of log data.
We also had the case were the receiving side (the log collector) regularly dropped connections soon after they were established. Clients had many logs in their RingBuffer at the time they reconnect causing the BufferedOutputStream to fill very quickly. Unfortunately, the receiver dropped the connection a few millis after it was established hence causing the lost of the entire BufferedOutputStream data. It was enough to repeat that scenario 10 times to drain the client RingBuffers... and loose everything.

What could be done to solve that issue?

I'm also questioning the actual benefits of the BufferedOutputStream... I understand it may act as a buffer to hold JSON data in case the TCP connection is not fast enough to accept it. But isn't the RingBuffer enough? I mean, what's the problem in having the event handler thread slowed down at the pace of the tcp connection ?

Side note: there is currently no way to disable the OutputStreamBuffer (no configuration property and the TcpSendingEventHandler class is inner private..). My only solution so far was to set its size to `1`... :(

**Comment by brenuart** [comment]
I also notice the event is dropped if the `TcpSendingEventHandler` gets an (IO)exception when writing its serialized form into the output stream... (correct?). Shouldn't we keep it in the RingBuffer and retry once a new connection is established.

Sorry for the hijack... should I open another thread for this ?

**Comment by brenuart** [comment]
Ping. Anybody alive (or an holiday maybe)... ?

**Comment by philsttr** [comment]
Hey @brenuart,

I could certainly change logstash-logback-encoder to make the buffered outputstream optional.  Say, if you set the writeBufferSize=0.

I honestly haven't performed any profiling on this to determine how much benefit the buffer is providing.

My _general_ understanding of why you should buffer an output stream is to decrease the number of system calls.  System calls are slow, so theoretically the buffer helps speed things by limiting the number of system calls.
It _could_ be that the max rate that the writer thread can achieve is slowed down when buffering is turned off due to the increase in the number of system calls made.  This could result in the writer thread not being able to keep up with the producer threads, thus leading to a full ringbuffer, thus leading to dropped events when the producers try to enqueue an event on a full ringbuffer.

However, that is just a theory, and would definitely need to be verified by profiling with your log events.

Keep in mind, the size of your log events will comes into play as well.  i.e. If your log events are > 8196, then buffering might actually be increasing the number of system calls made.  Again, profiling with your log events would probably be best.

Currently, flushes of the buffer... and therefore writes to the underlying output stream... and therefore  system calls... will occur at the following times:

1. when the buffer is full
2. when the end of the "batch" of events received from the ring buffer is reached (see [here](https://github.com/logstash/logstash-logback-encoder/blob/7d2a4e5698c4e649f1b89e7a9c30193a3ba1157e/src/main/java/net/logstash/logback/appender/AbstractLogstashTcpSocketAppender.java#L454-L456))


If the buffered output stream is removed, writes to the underlying outputstream will occur once per log event with logback 1.2.0+, or _many_ times per log event with 1.1.x or before.  (In logback 1.2.0+, encoding was changed slightly.)

Ultimately, if the receiving end is flaky, you're most likely going to end up with dropped events in any case.  When using a buffered output stream, you'll get dropped events from the buffer AND potentially from the ringbuffer (if producers try to enqueue events on a full ringbuffer).  When not using a buffered output stream, you'll still get dropped events from the producer/ringbuffer side.  However, this might be slightly better, and provide a little more cushion before events are dropped.

Having said all of that, I can go ahead and make the buffer optional, to provide you with more options.

**Comment by brenuart** [comment]
Thanks for your reply @philsttr. I'm glad to see you are still alive... I was used to your very prompt replies in the past and became worried this time ;-)

I understand your explanation about the potential impact of system calls, if any. I did not benchmark it tho. We endup in sizing the BufferedOutputStream such that it can never hold a full event. This way the TcpSendingEventHandler will not be able to write a full event if the connection is lost and will retry that same event whenever the connection comes back. The only drops occurs when the RingBuffer is full.

The `logstash-logback-encoder` is great library, honestly - thanks for this. However I wish the various Event handler were more extensible - mainly the TcpSendingEventHandler. They are currently implemented as private inner classes which makes it very difficult to customise if ever we feel the need. For instance I'd like to customise the connection establishment logic with a different strategy (I saw posts and/or pull requests around that earlier). It would be nice if - for instance - we could submit our own implementation. What do you think ?

**Comment by philsttr** [comment]
I'm definitely all for allowing customizations.  However, I generally prefer putting some thought behind extension points and formalizing them (such as connection establishment, customizing json generators, etc), versus just making everything public.  Arbitrarily making everything public makes refactoring and maintaining the library more difficult.

But yeah, I'm definitely open to specific ideas for extensions.  And I welcome PRs.

**Comment by philsttr** [comment]
Closing this.  The write buffer can now be disabled by setting the `writeBufferSize=0`.

Feel free to open new issues on desired extension points.

**Comment by philsttr** [comment]
[4.10](https://github.com/logstash/logstash-logback-encoder/releases/tag/logstash-logback-encoder-4.10) released with the ability to disable the write buffer.
