### ISSUE TITLE
Incorrect "Logback version is prior to 1.2.0." message

### ISSUE THREAD

**Issue by laktak** [logstash/logstash-logback-encoder#221]
I get the message

> -WARN in net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder@16022d9d - Logback version is prior to 1.2.0.  Enabling backwardscompatible encoding.  Logback 1.2.1 or greater is recommended.

when using 

```
compile "ch.qos.logback:logback-classic:1.2.3"
compile "net.logstash.logback:logstash-logback-encoder:4.9"
```

IMHO this is because in [Logback11Support.java](https://github.com/logstash/logstash-logback-encoder/blob/master/src/main/java/net/logstash/logback/Logback11Support.java) you check for an `init` method

```
    private static final Method ENCODER_INIT_METHOD = getMethod(Encoder.class, "init", OutputStream.class);
[..]
    private static final boolean IS_LOGBACK_1_1 = ENCODER_INIT_METHOD != null;
[..]
    public static boolean isLogback11OrBefore() {
        return IS_LOGBACK_1_1;
    }
```
that was removed from [Encoder.java](https://github.com/qos-ch/logback/blob/master/logback-core/src/main/java/ch/qos/logback/core/encoder/Encoder.java) in [this commit](
https://github.com/qos-ch/logback/commit/65a48e835363f31834f221132402308a93d5b843#diff-6016b292fde98b9e7ed5c04a79bd96f2):

```
-    byte[] init() throws IOException;
+    byte[] headerBytes();
```

**Comment by philsttr** [comment]
I cannot reproduce this when I run with logback-classic 1.2.3 and logback-core 1.2.3.

Can you ensure that your runtime classpath has logback-classic 1.2.3 and _logback-core 1.2.3_ on it?   Your dependencies only list logback-classic.  Perhaps gradle is resolving a different version of logback-core  (since Encoder is from logback-core)  

You are correct that `Encoder.init` was removed from logback in 1.2.0.

If the method [does _not_ exist](https://github.com/logstash/logstash-logback-encoder/blob/master/src/main/java/net/logstash/logback/Logback11Support.java#L39) at runtime, logstash-logback-encoder assumes you're running with logback 1.2.0 or higher.

If the method does exist at runtime, logstash-logback-encoder assumes you're running with logback 1.1.x or lower.  So, if the method does not exist at runtime, logstash-logback-encoder will output the warning that you see.

**Comment by gavinldc724** [comment]
I also encountered the same problem, the latest version of the logstash, receive logback log, display：
exception=>#<IOError: invalid stream header: 7B224074>

**Comment by laktak** [comment]
Thanks! I somehow missed the != check.

Adding logback-core:1.2.3 fixed the issue

```
  compile "ch.qos.logback:logback-core:1.2.3"
```
