### ISSUE TITLE
minor version not compatible with 4.x

### ISSUE THREAD

**Issue by dr3s** [logstash/logstash-logback-encoder#224]
Just upgraded to 4.9 from 4.3.  The Markers utility class or the hierarchy of LogstashMarker has changed somewhere along the way.  My existing code was assigning the result of Markers.append to an ObjectAppendingMarker but now I get a compile error.  Typically these types of changes would result in a major release.

`ObjectAppendingMarker marker = Markers.append(LogFieldNames.HTTP_DATA, logData);`

**Comment by philsttr** [comment]
100% agree on backwards incompatible changes should trigger a major version bump.  This project follows semantic versioning practices, so you are correct, a major version bump should have occurred.

In this case, the backwards incompatibility was inadvertently overlooked.  I apologize for that.

Having said that, I do not want to bump the major version or change the code back to the old code at this point, since so many versions have passed since then.  Therefore, you'll need to update your code.

I have updated the [release notes of version 4.4](https://github.com/logstash/logstash-logback-encoder/releases/tag/logstash-logback-encoder-4.4) (when this incompatibility was introduced) to specifically call out this backwards incompatibility.

**Comment by dr3s** [comment]
understood. thanks for the quick response.
