### ISSUE TITLE
Consider starting the Disruptor when the LoggerContext is started

### ISSUE THREAD

**Issue by brenuart** [logstash/logstash-logback-encoder#227]
The disruptor is currently started on the `start()` method inherited from the `Appender` logback interface. That method is invoked _during_ the context construction but *BEFORE* the context is actually started - via `LoggerContext.start()`.

`Appender.start()` is more an order to _validate the configuration_ rather than an actual start of processing.

Can't we listen for the context start event and delay the actual attempt to connect to the remote destination until the event is received ?

**Comment by philsttr** [comment]
Hmm.  The start/stop methods are part of the `Lifecycle` interface.  These methods seem like the appropriate "hooks" into logback to manage the lifecycle of the `AsyncDisruptorAppender`  (and its subclasses, including the TCP appenders).

Note that the TCP connection establishment happens asynchronously, on a different thread, so it doesn't block the main startup thread.   This is similar to logback's own `SocketAppender`, which (in the start method) submits a task to establish the TCP connection asynchronously.

Are you running into a specific problem caused by the current behavior?
