### ISSUE TITLE
UDP Appender to Multiple Destinations ?

### ISSUE THREAD

**Issue by francisoud** [logstash/logstash-logback-encoder#236]
With the TCP appender there is a simple syntax to send logs to multiple destination (https://github.com/logstash/logstash-logback-encoder#multiple-destinations).

But with UDP Appender I found no such explanation... does it exist ?

As a workaround I duplicated my UDP appender with the following configuration (it seems to work but it feels a bit of a hack):

    <appender name="UDP1" class="net.logstash.logback.appender.LogstashSocketAppender">
        <host>1.2.3.4</host>
        <port>1234</port>
        <customFields>{"application":"myapp"}</customFields>
    </appender>
    <appender name="UDP2" class="net.logstash.logback.appender.LogstashSocketAppender">
        <host>9.8.7.6</host>
        <port>9876</port>
        <customFields>{"application":"myapp"}</customFields>
    </appender>

    <root level="WARN">
        <appender-ref ref="ASYNC" />
        <appender-ref ref="UDP1" />
        <appender-ref ref="UDP2" />
    </root>

**Comment by philsttr** [comment]
Note that the TCP appender only sends logs to one destination at a time.  It just creates a single connection to one of the destinations from the configured list based on a connection strategy.  If a connection fails (or periodically), it'll reconnect to a new destination.

There is no equivalent functionality for UDP since UDP doesn't t have connections.


If sending logs to multiple destinations at the same time is ever implemented for TCP, then it will also be considered for UDP.

There are two workarounds:
1) configure an appender for each destination   (maybe consider programmatic configuration to reduce xml cut-and-paste), OR
2) Use a balancer on the receiving end to forward to multiple destinations.
