### ISSUE TITLE
The message attribute in the JSON log has backslash, new line and special charecters

### ISSUE THREAD

**Issue by SawyerFord** [logstash/logstash-logback-encoder#264]
Hi Team,

I have applied the logstash-logback-encoder and the logs generate in JSON format but some portion of the logs as below for message attritbute still has backslash, new line and special charecters in it. 

  `{"@timestamp":"2018-01-31T19:21:27.624+04:00","@version":1,"message":"{\"type\":\"API_REQUEST\",\"uid\":\"35f53fe5-7c63-4936-a617-14601073a5f7\",\"sessionId\":\"9E998B68C5A6D66C30D215DE0B4B5EF3\",\"remoteAddress\":\"0:0:0:0:0:0:0:1\",\"methodType\":\"POST\",\"headers\":\"{content-length=76, accept-language=en-US,en;q=0.9, cookie=JSESSIONID=50D17B32E96A6A8850F2A5FD52A4C07D, postman-token=a5be9806-a0a6-3905-e45d-2bea9036f3ed, origin=chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop, accept=*/*, host=localhost:3080, connection=keep-alive, content-type=application/json, cache-control=no-cache, accept-encoding=gzip, deflate, br, user-agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36}\",\"uri\":\"/user/login\",\"query\":null,\"contentType\":\"application/json\",\"requestTime\":\"2018-01-31 19:21:26.024\",\"responseTime\":\"2018-01-31 19:21:27.604\",\"executionTimeMillisecond\":1580,\"requestPayload\":\"{\\n  \\\"\\": \\\"+971\\\",\\n  \\\"phone\\\": \\\"545901009\\\",\\n  \\\"employeeType\\\": \\\"PHONE\\\"\\n }\",\"responsePayload\":\"{\\\"status\\\":\\\"FAIL\\\",\\\"statusCode\\\":1000,\\\"message\\\":\\\"Internal Server Error\\\",\\\"desc\\\":\\\"FAIL\\\",\\\"debug\\\":\\\"org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.IllegalArgumentException: non null key required\\\\n\\\\tat org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:982)\\\\n\\\\tat org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)\\\\n\\\\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:648)\\\\n\\\\tat org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)\\\\n\\\\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:729)\\\\n\\\\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)\\\\n\\\\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)\\\\n\\\\tat org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)\\\\n\\\\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)\\\\n\\\\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)\\\\n\\\\tat`

**Comment by SawyerFord** [comment]
I have called an API from postman which takes json input

**Comment by SawyerFord** [comment]
Hi @philsttr 

I have checked in my application and found that the  message field logs are configured in JSON format. How do I override and do the configurations for logstash-logback-encode to not parse the message field once again into JSON.

**Comment by SawyerFord** [comment]
Hi @philsttr

Below is the logger which already parses the message attribute in JSON. It is made to store inside GrayLogs.

<logger name="com.json.logging.config.log.JSONLogFilter" level="DEBUG" > <appender-ref ref="GELF" /> </logger>
Do I get this same message field inside the log output without encoding and I would also like to remove some of the new link charecters of the subfields of message JSON

**Comment by philsttr** [comment]
What is `com.json.logging.config.log.JSONLogFilter`?

**Comment by SawyerFord** [comment]
@philsttr : This is a filter extends the OncePerRequestFilter and has the the below logic

      ObjectNode obj=new ObjectNode();
      obj.put(''type","API_REQUEST")
      obj.put("uid", requestWrapper.getUid());

There are many properties set with the requestPayload and responsePaylod. Then finally we have 

     log.debug(obj.toString());

There is this part of the Filter which converts the messages into JSON. What I ultimately want is this message in my logs(which are converted into JSON format using logstash-logback-encoder) but I dont want to deserialize or anything more to the above logic as this filter is applied largerly in our project,

I short how do we handle the messages which are already preconverted into JSON inside the logtash-logbackEncoder

**Comment by philsttr** [comment]
If you know that _all_ of the messages logged to a given logger are already pre-converted to JSON, then you could write your own `JsonProvider` that looked at the logger name from the LoggingEvent, and then pass the LoggingEvent's message to one of the `generator.writeRaw*` methods.

**Comment by SawyerFord** [comment]
I want to know if the below config is applied
`<logger name="com.json.logging.config.log.JSONLogFilter" level="DEBUG" > <appender-ref ref="GELF" /> </logger>
`
As the filter(where contents are put inside ObjectNode) extends OncePerRequestFilter, I would like to whether all the messages are pre-converted to JSON. I can see some messages as below in the logs

     `{
  "@timestamp": "2018-02-03T21:37:09.351+04:00",
  "@version": 1,
  "message": "SQL Error: 1146, SQLState: 42S02",
  "logger_name": "org.hibernate.engine.jdbc.spi.SqlExceptionHelper",
  "thread_name": "http-nio-3080-exec-9",
  "level": "WARN",
  "level_value": 30000,
  "HOSTNAME": "algo-11"
}
`

**Comment by philsttr** [comment]
In your custom JsonProvider, you can look at the LoggingEvent's logger name.  

If the logging event's logger name is `com.json.logging.config.log.JSONLogFilter`, then assume that the message has already been pre-converted to json.  Then you can call one of the `generator.writeRaw` methods to add the raw pre-converted json string to the logged json output.

The example you mentioned in your last comment has a different logger name (`org.hibernate.engine.jdbc.spi.SqlExceptionHelper`), so you wouldn't call `generator.writeRaw` for that event.

**Comment by SawyerFord** [comment]
I tried in this way below but I dont get the logger messages

              `public static final String FIELD_MESSAGE = "message";

    public CustomMessageJsonProvider() {
        setFieldName(FIELD_MESSAGE);
    }

    @Override
    public void writeTo(JsonGenerator generator, ILoggingEvent event) throws IOException {
        if(event.getLoggerName().equals("com.json.logging.config.log.JSONLogFilter")){
            System.out.println("Sawyer JSONLogFilter Event Messages only:::"+ event.getMessage());
                generator.writeRawValue(event.getMessage());
            
        }
        JsonWritingUtils.writeStringField(generator, getFieldName(), event.getFormattedMessage());
    }
    @Override
    public void setFieldNames(LogstashFieldNames fieldNames) {
        setFieldName(fieldNames.getMessage());
    }`

**Comment by philsttr** [comment]
You'll need to disable the other json provider that provides the standard message field (the one that is getting escaped).

```xml
<fieldNames>
    <message>[ignore]</message>
</fieldNames>
```

**Comment by SawyerFord** [comment]
but even doing this will ignore messages for other logs too.

**Comment by philsttr** [comment]
To eliminate the escaped chars inside the requestPayload and responsePayload, you will have to modify your `com.json.logging.config.log.JSONLogFilter` to not escape them, since those are getting escaped by it.  (i.e. it's not getting escaped by the `LogstashEncoder`).

If you want to change the ordering of the fields, you'll have to stop using `LogstashEncoder`, and instead use the [`LoggingEventCompositeJsonEncoder`](https://github.com/logstash/logstash-logback-encoder#composite-encoderlayout) with the providers added in the order in which you want them.

**Comment by nbhagwath** [comment]
Hi now I would like to add a new fieldName  as SuccessMessage such that it should be shown in Kibana. This SuccessMessage field consists of the data from the successResponse object.

     log.debug("Success Message is {} , Failure Message is {}", successResponse, failureResponse)

How do I create a new field  which contains the content of successResponse(it is an object of SuccessResponse class with fields  name, statuscode, status) and see it on kibana

**Comment by philsttr** [comment]
Use `StructuredArguments` as mentioned [here](https://github.com/logstash/logstash-logback-encoder#event-specific-custom-fields)

**Comment by SawyerFord** [comment]
Hi Phil,

I am getting enough out of it. Should we make changes where log.info or
log.debug available inside the application source code.

Can you please provide me an example how to do basing on the  log.debug
statement which is inside application

 log.debug("Success Message is {} , Failure Message is {}",
successResponse, failureResponse)


Thanks

Niket Bhagwath

**Comment by nbhagwath** [comment]
@philsttr : I have seen that the objects inside the **employee**  object which contains various fields with values don't convert to JSON 
 
            log.debug("This is employee Object : {}" ,  **employee**)

They are displayed as   

`"message":"This is employee Object: Employee(employeeId=16, city=Galazy, country=Pandora Ghats,countryCode=+91, email=null, phone=12222344, aboutMe=test),`

Inside the below JSON

    `{"@timestamp":"2018-02-11T11:33:08.746+04:00","@version":1,"message":"This is employee Object: Employee(employeeId=16, city=Galazy, country=Pandora Ghats,countryCode=+91, email=null, phone=12222344, aboutMe=test),"thread_name":"Background-8","level":"DEBUG","level_value":10000,"HOSTNAME":"algo-11"}`

 I am in the assumption that logstash-logback-encoder converts the objects passed also in JSON.  
How do I make changes such that all the object passed to debug get converted to JSON format.

**Comment by SawyerFord** [comment]
@philsttr : I have seen that the objects inside the employee object which contains various fields with values don't convert to JSON

        log.debug("This is employee Object : {}" ,  employee)
They are displayed as

"message":"This is employee Object: Employee(employeeId=16, city=ABCC, country=XYZZ ,countryCode=+921, email=null, phone=12222344, aboutMe=test),

Inside the below JSON

`{"@timestamp":"2018-02-11T11:33:08.746+04:00","@version":1,"message":"This is employee Object: Employee(employeeId=16, city=Galazy, country=Pandora Ghats,countryCode=+91, email=null, phone=12222344, aboutMe=test),"thread_name":"Background-8","level":"DEBUG","level_value":10000,"HOSTNAME":"algo-11"}`

I am in the assumption that logstash-logback-encoder converts the objects passed also in JSON.
How do I make changes such that all the objects  passed in the application to log.debug or log.info get converted to JSON format.

**Comment by philsttr** [comment]
The `message` argument passed to the log methods will always end up in the `message` field of the json output.  This is exactly what is happening in your example.  Logstash itself is substituting the toString() representation of the `employee` argument into the message.

If you want to include _additional_ fields in the json output, then you need to use structured arguments as mentioned [here](https://github.com/logstash/logstash-logback-encoder#event-specific-custom-fields)

For example...

```java
log.debug("Some message", keyValue("employee", employee))
```
which would result in json output like this
```
{
    ...
    "message" : "Some message",
    "employee" : {
        ...
    }
}
```

**Comment by SawyerFord** [comment]
@philsttr : 

    I tried in this way but it does not work 
 
             `Employee employee=new Employee();
            employee.setFirstName("Niket");
            employee.setLastName("Bhagwath");
            employee.setPhoneNumber("545901533");
            employee.setAddress("Hyderabad");
            employee.setDescription("HireriepriwerierwerHellorwero"); `

            LOGGER.debug("Employee Object::::::{}", value("employeeString", employee)
            This is returning Employee 
            Object::::::com.jsonlogging.demo.springboot.model.Employee@16c0507b

            LOGGER.debug("Employee Object::::::{}", kv("employeeString", employee));
            This is returning the value as
            employee= com.jsonlogging.demo.springboot.model.Employee@16c0507b

**Comment by philsttr** [comment]
> I think its not because of Logstash but its format is the toString representation of using Lombok plugin in our project

You are correct here.  I meant to say _logback_, not _logstash_ in my statement.  Logback will substitute the `toString()` representation of the arguments into the appropriate placeholder (`{}`) in the message field of a log event.  This is just standard logback behavior.  

I also think I see source of the confusion.   StructuredArguments will only be included in the JSON output if using [composite encoders/layouts](https://github.com/logstash/logstash-logback-encoder#composite-encoderlayout) with the `arguments` provider, or if you add the `ArgumentsJsonProvider` provider to your `LogstashEncoder` configuration like this

```xml
<encoder class="net.logstash.logback.encoder.LogstashEncoder">
    <provider class="net.logstash.logback.composite.loggingevent.ArgumentsJsonProvider"/>
</encoder>
```

With the above configuration, the following log statements...

```java
        LOGGER.debug("1 Employee Object::::::{}", value("employeeString", employee));
        
        LOGGER.debug("2 Employee Object::::::{}", keyValue("employeeString", employee));
        
        LOGGER.debug("3 Employee Object::::::", value("employeeString", employee));
        
        LOGGER.debug("4 Employee Object::::::{}", employee);
```

will result in the following output (formatted for clarity):

```json
{
  "@timestamp" : "2018-02-15T21:13:47.720-08:00",
  "@version" : 1,
  "message" : "1 Employee Object::::::com.jsonlogging.demo.springboot.model.Employee@3f72aff0",
  "logger_name" : "Main",
  "thread_name" : "main",
  "level" : "DEBUG",
  "level_value" : 10000,
  "employeeString" : {
    "firstName" : "Sawyer",
    "lastName" : "Ford",
    "phoneNumber" : "12334433",
    "address" : "deddwde",
    "description" : "HireriepriwerierwerHellorwero"
  }
}
{
  "@timestamp" : "2018-02-15T21:13:47.747-08:00",
  "@version" : 1,
  "message" : "2 Employee Object::::::employeeString=com.jsonlogging.demo.springboot.model.Employee@3f72aff0",
  "logger_name" : "Main",
  "thread_name" : "main",
  "level" : "DEBUG",
  "level_value" : 10000,
  "employeeString" : {
    "firstName" : "Sawyer",
    "lastName" : "Ford",
    "phoneNumber" : "12334433",
    "address" : "deddwde",
    "description" : "HireriepriwerierwerHellorwero"
  }
}
{
  "@timestamp" : "2018-02-15T21:13:47.747-08:00",
  "@version" : 1,
  "message" : "3 Employee Object::::::",
  "logger_name" : "Main",
  "thread_name" : "main",
  "level" : "DEBUG",
  "level_value" : 10000,
  "employeeString" : {
    "firstName" : "Sawyer",
    "lastName" : "Ford",
    "phoneNumber" : "12334433",
    "address" : "deddwde",
    "description" : "HireriepriwerierwerHellorwero"
  }
}
{
  "@timestamp" : "2018-02-15T21:13:47.747-08:00",
  "@version" : 1,
  "message" : "4 Employee Object::::::com.jsonlogging.demo.springboot.model.Employee@3f72aff0",
  "logger_name" : "Main",
  "thread_name" : "main",
  "level" : "DEBUG",
  "level_value" : 10000
}
```

Notice that the final log event does not include the argument, since it is not a structured argument.
If you want to include non-structured arguments, you can do so like this:

```xml
<encoder class="net.logstash.logback.encoder.LogstashEncoder">
    <provider class="net.logstash.logback.composite.loggingevent.ArgumentsJsonProvider">
        <includeNonStructuredArguments>true</includeNonStructuredArguments>
    </provider>
</encoder>
```

In which case the final log event from above would be logged as:

```json
{
  "@timestamp" : "2018-02-15T21:14:35.748-08:00",
  "@version" : 1,
  "message" : "4 Employee Object::::::com.jsonlogging.demo.springboot.model.Employee@25c17335",
  "logger_name" : "Main",
  "thread_name" : "main",
  "level" : "DEBUG",
  "level_value" : 10000,
  "arg0" : {
    "firstName" : "Sawyer",
    "lastName" : "Ford",
    "phoneNumber" : "12334433",
    "address" : "deddwde",
    "description" : "HireriepriwerierwerHellorwero"
  }
}
```

**Comment by philsttr** [comment]
Note #169 will enable the structured args by default

**Comment by SawyerFord** [comment]
It worked well and thanks a lot for the formatted output.
But is there any way I get the  name of the **arg0** in the  JSON output as class name or name of the object for example

           `"arg0" : {
    "firstName" : "Sawyer",
    "lastName" : "Ford",
    "phoneNumber" : "12334433",
    "address" : "deddwde",
    "description" : "HireriepriwerierwerHellorwero"
  }`

as 

           `"Employee" : {
    "firstName" : "Sawyer",
    "lastName" : "Ford",
    "phoneNumber" : "12334433",
    "address" : "deddwde",
    "description" : "HireriepriwerierwerHellorwero"
  }`

       `"Organization" : {
    "firstName" : "Sawyer",
    "lastName" : "Ford",
    "phoneNumber" : "12334433",
    "address" : "deddwde",
    "description" : "HireriepriwerierwerHellorwero"
  }`

**Comment by philsttr** [comment]
>  How do I get the output such that I don't have the toString representation in the message field and only in the arg0

You have two options to do this:

1. Don't include a placeholder (`{}`) for the argument in your message.  Therefore, logback won't insert the argument.toString() into the message
OR
2. Turn off the default [MessageJsonProvider](https://github.com/logstash/logstash-logback-encoder/blob/master/src/main/java/net/logstash/logback/composite/loggingevent/MessageJsonProvider.java) (as mentioned [here](https://github.com/logstash/logstash-logback-encoder/issues/264#issuecomment-362970963)), and add a new provider similar to [MessageJsonProvider](https://github.com/logstash/logstash-logback-encoder/blob/master/src/main/java/net/logstash/logback/composite/loggingevent/MessageJsonProvider.java) that gets the _unformatted_ message from the loggingEvent.  i.e. use `loggingEvent.getMessage()` instead of `loggingEvent.getFormattedMessage()`

For example:

```java
public class UnformattedMessageJsonProvider extends MessageJsonProvider {

    @Override
    public void writeTo(JsonGenerator generator, ILoggingEvent event) throws IOException {
        JsonWritingUtils.writeStringField(generator, getFieldName(), event.getMessage());
    }
}
```

> Is there any way I get the name of the arg0 in the JSON output as class name or name of the object to which the values of the arg0 to which it corresponds to without adding strucutured arguements of keyvalue/ kv in the application code

You would have to write your own json provider to do this.  For example, something like this

```java
public class NamedArgumentJsonProvider extends AbstractJsonProvider<LoggingEvent> {

	@Override
	public void writeTo(JsonGenerator generator, LoggingEvent event) throws IOException {
		for (Object argument : event.getArgumentArray()) {
			if (argument != null) {
				generator.writeFieldName(argument.getClass().getSimpleName());
				generator.writeObject(argument);
			}
		}
	}
}
```

**Comment by SawyerFord** [comment]
@philsttr 

    Is the above change fine because I am getting the output string as {
	"@timestamp": "2018-02-17T04:19:23.359+04:00",
	"@version": 1,
	"logMessage": "Returning handler method [public java.lang.String com.jsonlogging.demo.springboot.controller.EntryController.sayHello(org.springframework.http.HttpHeaders) throws java.io.IOException]" {
			"@timestamp": "2018-02-17T04:19:23.359+04:00",
			"@version": 1,
			"logMessage": "Returning cached instance of singleton bean 'entryController'" {
					"@timestamp": "2018-02-17T04:19:23.359+04:00",
					"@version": 1,
					"logMessage": "Last-Modified value for [/hello] is: -1" {
							"@timestamp": "2018-02-17T04:19:23.376+04:00",
							"@version": 1,
							"logMessage": "INFO" {
									"@timestamp": "2018-02-17T04:19:23.376+04:00",
									"@version": 1,
									"logMessage": "DEBUG" {
											"@timestamp": "2018-02-17T04:19:23.377+04:00",
											"@version": 1,
											"logMessage": "WARN" {
													"@timestamp": "2018-02-17T04:19:23.377+04:00",
													"@version": 1,
													"logMessage": "ERROR" {
															"@timestamp": "2018-02-17T04:19:23.402+04:00",
															"@version": 1,

**Comment by philsttr** [comment]
A few comments...

1) You do not need to include
```xml
                <provider class="net.logstash.logback.composite.loggingevent.ArgumentsJsonProvider">
                    <includeNonStructuredArguments>true</includeNonStructuredArguments>
                </provider>
```
Because the `<arguments/>` element will add the arguments json provider.

You don't need either of them if you are not going to use StructuredArguments.

2) You're also including the formatted message with the pattern provider.  I thought you did not want the formatted message.

3) The output you provided looks like it's from two different log events.  Were these output via the console appender?  If so, they might be from two different threads.  If that is the case, then you can put the console appender behind an AsyncDisruptorAppender so that log messages don't write on top of each other

**Comment by SawyerFord** [comment]
@philsttr : 

   My Whole config is this
    
     `<appender name="jsonAppender" class="ch.qos.logback.core.rolling.RollingFileAppender">
        <File>${LOG_PATH}</File>
        <encoder class="net.logstash.logback.encoder.LogstashEncoder">

                <provider class="config.UnformattedMessageJsonProvider">
                </provider>
                <provider class="config.NamedArgumentJsonProvider">
                </provider>

        </encoder>`

**Comment by philsttr** [comment]
`LoggingEventCompositeJsonEncoder` encodes LoggingEvents as JSON by using JsonProviders.  By default, `LoggingEventCompositeJsonEncoder` has no providers.  It's up to you to add the providers that you want to get the output you want.

Each provider contributes something to the JSON output by the encoder. For example, the `timestamp` provider will add the LoggingEvent's timestamp to the JSON output.  logstash-logback-encoder comes with many providers, but you can also add your own if those provided by logstash-logback-encoder do not handle your use case.


`LogstashEncoder` is a subclass of `LoggingEventCompositeJsonEncoder` with a set of providers pre-configured as sensible defaults.  

Both `LogstashEncoder` and `LoggingEventCompositeJsonEncoder` use providers to contribute to the output.  It's just that `LogstashEncoder` starts with a set of default providers to handle common use cases, and `LoggingEventCompositeJsonEncoder` starts with no providers.

For simple use cases, users can just use `LogstashEncoder`.

For complex use cases, it might be easier to start with `LoggingEventCompositeJsonEncoder`, and add the exact providers what you want, rather than starting with `LogstashEncoder`, and trying to remove/add/override functionality.  For example, if you want to customize the ordering of fields in the JSON output, you can configure `LoggingEventCompositeJsonEncoder` with providers in the order you want.  Or if you want to override some of the providers used by `LogstashEncoder`  (like your desire to not output the formatted message field), it might be easier to use `LoggingEventCompositeJsonEncoder`

In summary, for your use case, I would recommend `LoggingEventCompositeJsonEncoder`, but you could probably still use `LogstashEncoder` if you wanted.


Here's what your configuration could potentially look like using the `LoggingEventCompositeJsonEncoder`.  You can also add any [other provider](https://github.com/logstash/logstash-logback-encoder#providers-for-loggingevents) you want, depending on what you want included in the JSON output.

(Notice that the `rawMessage` provider is used here.  This can be used instead of your `UnformattedMessageJsonProvider`.  I didn't realize that logstash-logback-encoder already had a provider that outputs the unformatted message.)

```xml
<encoder class="net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder">
	<providers>
		<!-- Write a @timestamp field containing the LoggingEvent's timestamp-->
		<timestamp/>

		<!-- Write a @version field containing a value of 1-->
		<version/>

		<!-- Write a message field containing the raw/unformatted LoggingEvent message-->
		<rawMessage>
			<fieldName>message</fieldName>
		</rawMessage>

		<!-- Write the LoggingEvent's arguments as separate fields-->
		<provider class="config.NamedArgumentJsonProvider"/>
	</providers>
</encoder>
```



Regarding the clubbed messages, there is probably an exception occurring while generating the JSON output.  I would recommend registering a [logback status listener](https://logback.qos.ch/manual/configuration.html#dumpingStatusData) so you can see error messages and exceptions from logback.  You can use `<configuration debug="true">` or `<statusListener class="ch.qos.logback.core.status.OnConsoleStatusListener" />`

**Comment by SawyerFord** [comment]
@philsttr :+1: 

  The exact problem is not clubbed messages but the logs are not formed with a complete JSON format when we provide **NamedArgumentJsonProvider**  i.e  the ending brace is missing **}** . What could be the problem causing this one?

        {"@timestamp":"2018-02-18T01:50:28.569+04:00","@version":1,"logger_name":"org.springframework.web.context.support.StandardServletEnvironment","thread_name":"main","level":"DEBUG","level_value":10000,"HOSTNAME":"algo-11" 

{"@timestamp":"2018-02-18T01:50:28.569+04:00","@version":1,"logger_name":"org.springframework.web.context.support.StandardServletEnvironment","thread_name":"main","level":"DEBUG","level_value":10000,"HOSTNAME":"algo-

**Comment by SawyerFord** [comment]
@philsttr : 

when I give 
            generator.writeObjectField(fieldName, argument);
It is not capturing null values for example

      Employee employee=new Employee();
            employee.setFirstName("Sawyer");
            employee.setLastName("Fored");
            employee.setPhoneNumber("123443434");
            employee.setAddress("SWWEWEWE");
            employee.setDescription(null);

I get as 

      {"firstName":"Sawyer","lastName":"Fored","address":"SWWEWEWE","phoneNumber":"123443434"}

The description:null value is not captured. How do I get it

**Comment by philsttr** [comment]
I believe `objectMapper.setSerializationInclusion` sets the _default_ property inclusion value, which is only used if a class is _not_ annotated with `@JsonInclude`.  Since your `Employee` class is annotated with `@JsonInclude`, the value from the annotation on the `Employee` class will take precedence.

I don't think jackson provides a way to override the inclusion rules for _all_ classes.  But for _specific_ classes (e.g. your `Employee` class), you could use a [mix-in](https://github.com/FasterXML/jackson-docs/wiki/JacksonMixInAnnotations) that specifies a different value for `@JsonInclude`.  The `@JsonInclude` annotation on the mix-in class will override the `@JsonInclude` annotation on the `Employee` class.

I recommend asking jackson-specific questions on the [jackson users mailing list](https://github.com/FasterXML/jackson-docs#participating).


As a side note... you should configure the `ObjectMapper`/`JsonFactory` in a `JsonFactoryDecorator`, rather than in a `JsonProvider`.  See [here](https://github.com/logstash/logstash-logback-encoder#customizing-json-factory-and-generator).  The reason configuring the `ObjectMapper`/`JsonFactory` should be done in a `JsonFactoryDecorator` is because once an `ObjectMapper` is used for the first time, some of its configuration values cannot be changed.  The `JsonFactoryDecorator` will be invoked prior to the `ObjectMapper`/`JsonFactory` being used for the first time.

**Comment by SawyerFord** [comment]
@philsttr : When I use customized ArgumentsProvider, I find that the objects(classes) with the private fields are not serialized, and not logged into the log file. I have used the below config 
                         objectMapper.setVisibility(PropertyAccessor.ALL, JsonAutoDetect.Visibility.ANY)

within a decorator but it didn't work. How do I make changes such that the private fields also get serialized

**Comment by philsttr** [comment]
I believe that is the way to do it.

Can you provide the complete source of your decorator?  And also your encoder xml configuration which enables your decorator?

**Comment by SawyerFord** [comment]
@philsttr 

Below is the source 

      `public class CustomFactoryDecorator implements JsonFactoryDecorator{

        @Override
        public MappingJsonFactory decorate(MappingJsonFactory factory) {
            ObjectMapper codec = factory.getCodec();
            codec  = codec.copy()
                    .disable(MapperFeature.USE_ANNOTATIONS)
                    .setSerializationInclusion(JsonInclude.Include.ALWAYS)
                    .setVisibility(PropertyAccessor.ALL, JsonAutoDetect.Visibility.ANY)
                    .setVisibility(PropertyAccessor.FIELD, JsonAutoDetect.Visibility.ANY);

            factory.setCodec(codec);
            return factory;
        }
    }
`

**Comment by philsttr** [comment]
If ArgumentsJsonsJsonProvider.fieldName is not null, then all of the arguments will be serialized inside a sub-object of the main log event.

For example if fieldName is `args`, then the log event would be output as JSON like this:

```
{
  "@timestamp" : "2018-02-15T21:13:47.747-08:00",
  "@version" : 1,
  "message" : "3 Employee Object::::::",
  "logger_name" : "Main",
  "thread_name" : "main",
  "level" : "DEBUG",
  "level_value" : 10000,
  "args" : {
    "employeeString" : {
      "firstName" : "Sawyer",
      "lastName" : "Ford",
      "phoneNumber" : "12334433",
      "address" : "deddwde",
      "description" : "HireriepriwerierwerHellorwero"
    }
  }
}
```

Whereas, if the fieldName is null, then the log event would be output as JSON like this:

```
{
  "@timestamp" : "2018-02-15T21:13:47.747-08:00",
  "@version" : 1,
  "message" : "3 Employee Object::::::",
  "logger_name" : "Main",
  "thread_name" : "main",
  "level" : "DEBUG",
  "level_value" : 10000,
  "employeeString" : {
    "firstName" : "Sawyer",
    "lastName" : "Ford",
    "phoneNumber" : "12334433",
    "address" : "deddwde",
    "description" : "HireriepriwerierwerHellorwero"
  }
}
```

Please ensure you are using [logstash-logback-encoder 4.11](https://github.com/logstash/logstash-logback-encoder/releases/tag/logstash-logback-encoder-4.11) to ensure you're not running into bugs that have already been addressed.

For example, in [logback-logstash-encoder 4.8](https://github.com/logstash/logstash-logback-encoder/releases/tag/logstash-logback-encoder-4.8), two changes were made to addresses problems you have encountered.

* First, `SerializationFeature.FAIL_ON_EMPTY_BEANS` is now disabled by default.
* Second, if a different serialization error were to occur, the error will be logged to logback's status listener, but logging future events will continue to work.  (i.e. an error during serialization will not cause logging to stop)

Other bugs have been fixed in later versions.


Regarding proxy objects...
You can use [`AopUtils.isAopProxy(object)`](https://docs.spring.io/spring/docs/4.3.9.RELEASE/javadoc-api/index.html?org/springframework/aop/support/AopUtils.html) to determine if an object is a proxy, and [`AopUtils.getTargetClass(object)`](https://docs.spring.io/spring/docs/4.3.9.RELEASE/javadoc-api/index.html?org/springframework/aop/support/AopUtils.html) to get the class behind the proxy.



Regarding the Infinite recursion error.... It is important to realize that not every object can be serialized as JSON. Some objects have internal structures that prohibit it from being serialized properly. This is especially true for private member fields, which are sometimes never meant to be exposed outside of the object. For these objects/classes, you would need to configure Jackson with a custom serializer, or mix-in that ignores fields that can't be serialized, so that jackson can properly serialize the objects.

**Comment by SawyerFord** [comment]
@philsttr : Now I am have upgraded to 4.8 because my jackson version is 2.8.5. Now the exceptions are handled well but 
       when the stackoverflow error occured the earlier logs before the stackoverflow are erased and the logs after the stackoverflow error are printed in the logs.

**Comment by philsttr** [comment]
You are encountering the main problem with trying to serialize _every_ argument as JSON.  Jackson is not able to serialize every object due to things like infinite recursion in object graphs, like you are encountering.

My recommendation is to not try to serialize every argument as JSON.  Again, because there is no guarantee that jackson will be able to serialize every type of object passed as an argument as JSON.  You are extremely likely to encounter objects that are not JSON serializable by jackson, unless custom class-specific hints (such as JsonSerializers or mixin) are registered for the class.

Instead, I would recommend utilizing StructuredArguments.  When StructuredArguments are used, it forces the developer to follow the contract of a StructuredArgument.... in that the argument must be JSON serializable.  This forces developers to select which arguments it makes sense to try to JSON-serialize, and ensure those classes JSON-serializable.

However, if you would like to continue trying to serialize _every_ argument, then you are going to have to come up with your own strategy.  Most likely that strategy is _not_ going to be able to magically make every object JSON-serializable.  Therefore, you're going to have to make compromises.

For example, a simple strategy might be to whitelist classes that are known to be serializable, and not attempt to serialize classes that are not in the whitelist in your `JsonProvider`.

For classes that jackson cannot serialize by default, you can register mixins and custom serializers in a `JsonFactoryDecorator`.  After including the appropriate mixin or custom serializer, you can add them to your whitelist.

You could also take the opposite approach, by having a blacklist... i.e. classes that are known to NOT be serializable.  And only serialize classes that are not in that list.  This would be more error prone than a whitelist approach, since new classes (that might not be serializable) are invented every day.

Another strategy would be to catch the exceptions from jackson in your `JsonProvider`, and dynamically add the classes that cannot be serialized by jackson to a list of blacklisted classes at runtime.  (Therefore preventing them from being attempted to be serialized again).

There are probably other strategies that you can think of that will work for you.

The choice is yours to make.  You will need to pick a compromise with which you are willing to live. 

The logstash-logback-encoder library gives you the tools needed to implement your strategy.  You can configure the `JsonFactory`, `ObjectMapper`, and `JsonGenerator` exactly how you want it with [decorators](https://github.com/logstash/logstash-logback-encoder#customizing-json-factory-and-generator).  And you can create your own `JsonProvider` with full control over what to write to the `JsonGenerator`.  You can experiment with Jackson, and find what options work best for you.

**Comment by ekanshd-exzeo** [comment]
if i use log.error(Exception) , how can i further tokenize the message parameter to display a nested json for further individual fields?
