### ISSUE TITLE
Structured Arguments in logback-spring boot

### ISSUE THREAD

**Issue by cashok08** [logstash/logstash-logback-encoder#271]
How to avoid importing 
import static net.logstash.logback.argument.StructuredArguments.* 

in all my class files to use "keyValue" to print json logs

**Comment by philsttr** [comment]
If you want to use StructuredArguments in a your class, you will have to import it, or its static methods, just like you have to do for any other class, or static methods, that you want to use.

**Comment by cashok08** [comment]
I don't want to tie up my logging to logstash , I am using logback-spring.xml in my class path .Hence is it possible to hook up this class in that XML instead of importing it every where in my custom class

**Comment by philsttr** [comment]
The `logback-spring.xml` file only concerns the logback configuration.  If you want to utilize the functionality of StructuredArguments in your java classes, then your java classes will have to import StructuredArguments.

If you wanted to provide a layer of abstraction, you could define your own class with the same methods as the StructuredArguments class, and delegate those methods to StructuredArguments, then you could import your class in your code instead of StructuredArguments.
