### ISSUE TITLE
Configurable newline symbol in ShortenedThrowableConverter

### ISSUE THREAD

**Issue by fred84** [logstash/logstash-logback-encoder#279]
Log consumer in our system use `\n` as message separator.
Stack trace elements are concatenated by [CoreConstants.LINE_SEPARATOR](https://github.com/logstash/logstash-logback-encoder/blob/master/src/main/java/net/logstash/logback/stacktrace/ShortenedThrowableConverter.java#L505), so traces are split across several lines.
Currently I found solution proposed in https://github.com/logstash/logstash-logback-encoder/issues/83 , but I think It is worth adding an option to configure newline symbol inside json. If you don't see and obstacles, I can create PR.

**Comment by philsttr** [comment]
Seems reasonable to me.  A PR would be great!

**Comment by philsttr** [comment]
Hi @fred84 

Thank you so much for your contribution!

I have merged it, made a few naming changes, and documented it in the README.md.  It will be available in 5.1 when it is released.

I made the naming changes because I wanted to use consistent terminology with Jackson.  For example, Jackson uses `CharacterEscapes` and `escapeSequence`, so I wanted logstash-logback-encoder to use the same.

The one functional change I made was to start with the standard ASCII escaping behavior by default, rather than starting with ESCAPE_NONE for every ASCII character.  If your use case requires that you start with ESCAPE_NONE for every character, then you can set `<includeStandardAsciiEscapesForJSON>false</includeStandardAsciiEscapesForJSON>`
