### ISSUE TITLE
Can I directly push to a socket?

### ISSUE THREAD

**Issue by Meai1** [logstash/logstash-logback-encoder#28]
I just want to see the logs in kibana directly, without having to run a syslog server with 1024 byte limitation etc.

**Comment by philsttr** [comment]
Closing this issue, since `LogstashTcpSocketAppender` is available, and has now been tested.

Note that in 4.0 (not released yet),  `LogstashTcpSocketAppender` was improved.  It now uses a RingBuffer (from LMAX Disruptor) for asynchronous thread communication.  This provides better performance, and and will never block the logging thread.  See the new readme and javadoc for more details.
