### ISSUE TITLE
How to add/register custom JsonProvider?

### ISSUE THREAD

**Issue by hexwit** [logstash/logstash-logback-encoder#290]
Could you give me a hint, how to add/register newly created JsonProvider with logback? 
TBH I wasn't able to find doc on that. 

I want to use my provider with net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder.

Thanks.

**Comment by philsttr** [comment]
```xml
<encoder class="net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder">
  <providers>
    <provider class="your.provider.class.name">
        <!-- Any properties exposed by your provider can be set here -->
    </provider>
  </providers>
</encoder>
```

Will update the docs to make this more clear.

**Comment by hexwit** [comment]
Ok, but then there is no chance to have DI here, right?

**Comment by philsttr** [comment]
Logback is not aware of any dependency injection frameworks.

However, if you really want to use DI to assemble your logback configuration, you can configure logback programmatically, rather than using xml configuration.   #252 has an example of someone using spring to configure logback.

There's a little bit of an ordering problem here though.  Since logback is generally initialized prior to DI frameworks.
