### ISSUE TITLE
Can <arguments/> be split between <nestedField/>'s?

### ISSUE THREAD

**Issue by malkebu-lan** [logstash/logstash-logback-encoder#291]
Can <arguments/> be split between <nestedField/>'s or filtered?

For example, I would like some <arguments/> to be in the "appContext" and some to be in the "tracingContext."

<encoder class="net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder">
            <providers>
                <timestamp>
                    <timeZone>UTC</timeZone>
                </timestamp>
                <nestedField>
                    <fieldName>appContext</fieldName>
                    <providers>
                        <logLevel/>
                        <loggerName/>
                        <threadName/>
                        <callerData/>
                        <stackTrace/>
                        <throwableClassName/>
                        <throwableRootCauseClassName/>
                        <message/>
                    </providers>
                </nestedField>
                <nestedField>
                    <fieldName>tracingContext</fieldName>
                    <providers>
                        <arguments/>
                    </providers>
                </nestedField>
            </providers>
        </encoder>

**Comment by philsttr** [comment]
Currently, no.

However, you could write your own `JsonProvider` implementation that does so, and use it instead of the arguments provider.  ([`ArgumentsJsonProvider`](https://github.com/logstash/logstash-logback-encoder/blob/1faaf856177f8da847db69c6ae9ab01530fee953/src/main/java/net/logstash/logback/composite/loggingevent/ArgumentsJsonProvider.java))

**Comment by malkebu-lan** [comment]
thanks
