### ISSUE TITLE
Spring properties loaded later than the Spring profiles identification

### ISSUE THREAD

**Issue by berndgoetz** [logstash/logstash-logback-encoder#314]
When using Spring profiles to activate the logstash appender, it seems that the active Spring profiles are identified very early in the process, but the included Spring property is not yet populated. It also seems to be reconfigured later when the configuration is properly loaded. When activating debugging, we can see an exception as the URL is not yet set. Here's an excerpt from our logback-spring.xml file:

    ...
    <springProfile name="logstash">
        <springProperty scope="context" name="logstashUrl" source="infrastructure.logstash.destination" />
        <appender name="logstash" class="net.logstash.logback.appender.LogstashAccessTcpSocketAppender">
            <destination>${logstashUrl}</destination>
            <reconnectionDelay>1 second</reconnectionDelay>
    ...
            </encoder>
            <ssl/>
        </appender>
    </springProfile>
    ....

Could this be improved in some way? This is more an RfI than an issue.

**Comment by philsttr** [comment]
At first glance, I don't believe this is related to logstash-logback-encoder.  I'd recommend bringing this up with the spring-boot community since it appears to be related to the [spring boot logback extensions](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-logging.html#boot-features-logback-extensions).
