### ISSUE TITLE
StructuredArguments.value(String, Object) mysteriously stopped escaping nested arguments

### ISSUE THREAD

**Issue by bplies-IAS** [logstash/logstash-logback-encoder#319]
# Problem
`StructuredArguments.value(String, Object)` mysteriously stopped escaping the `String` of nested JSON from `Object` serialization

It has been working correctly for quite a while under complex Spring Boot 1.5.x apps yet does not work correctly with other Apps with seemingly identical, relevant dependencies and `logback-spring.xml`

As a result some events written to a log file are refused by Elasticsearch when forwarded by the Logstash agent:
```
[2019-01-04T18:14:53,614][WARN ][logstash.outputs.elasticsearch] Could not index event to Elasticsearch. {:status=>400, :action=>["index", {:_id=>nil, :_index=>"SOME_INDEX", :_type=>"app", :_routing=>nil}, 2019-01-04T23:14:52.796Z localhost Report report-id=1 requested], :response=>{"index"=>{"_index"=>"INDEX_NAME", "_type"=>"app", "_id"=>"AWgbJd__DXl-JdQiLMhX", "status"=>400, "error"=>{"type"=>"mapper_parsing_exception", "reason"=>"failed to parse [report-request-body]", "caused_by"=>{"type"=>"illegal_state_exception", "reason"=>"Can't get text on a START_OBJECT at 1:496"}}}}}
```

# Good, Usual encoding
Apps that are working correctly have events with nested props written to the log like this:
`{"prop1": "val1", "nested": "{\"nestedProp1\":5}"}`
Which adds the nested `Object` as an escaped `String` From Jackson's `ObjectMapper` serialization

# Bad, Mysterious encoding
Whereas when it isn't working properly events with nested props are written like this:
`{"prop1": "val1", "nested": {"nestedProp1":5}}`
Which is just the ordinary Jackson `ObjectMapper` serialization representation.  Elasticsearch is rejecting this.

# Demo
I've setup a demo repo to help illustrate the scenario.  Check the `README` for how to play with it.
https://github.com/bplies-IAS/logstash-logback-encoder-bugdemo

# Deep Dive Findings
For things that are escaping properly they seem to hit breakpoints within Jackson's 
[`UTF8JsonGenerator.writeStringSegmentASCII2`](https://github.com/FasterXML/jackson-core/blob/2.8/src/main/java/com/fasterxml/jackson/core/json/UTF8JsonGenerator.java#L1466)  yet when it isn't escaping at all _none_ of the various `UTF8JsonGenerator` escaping methods are touched.

The [Docs](https://github.com/logstash/logstash-logback-encoder#customizing-character-escapes) say

> "By default, when a string is written as a JSON string value, any character not allowed in a JSON string will be escaped. For example, the newline character (ASCII 10) will be escaped as \n."

The problem is we're somehow dealing with a JSON Object rather than a "JSON string value"

# Workaround
The only reliable workaround I have at the moment is to manually pre-serialize the `Object`
```
logger.info("Forced JSON serialization", value("report-request-body", objectMapper.writeValueAsString(reportMessageDTO)));
```
Which hadn't been and shouldn't be necessary.  We definitely want Developers to just write logging statements in a normal way.

**Comment by philsttr** [comment]
Did you observe a change in behavior in a single app when you upgraded something within the app? (logstash-logback-encoder, spring-boot, jackson, etc)

The intended behavior as designed for `StructuredArguments.value(String fieldName, Object value)` is to pass the `value` argument directly to [`JsonGenerator.writeObject`](https://github.com/logstash/logstash-logback-encoder/blob/00ba7b114bab2dc40959e13b2be77a3c07009ed9/src/main/java/net/logstash/logback/marker/ObjectAppendingMarker.java#L94) using the `jsonGenerator` that is writing the JSON event. `JsonGenerator.writeObject`'s default behavior when called with an object that is not a `String`, `Number`, `Boolean`, or array is to add the object to the log event JSON output as a JSON _object_ value.

If you want the value argument added as a JSON _string_ value instead of an _object_, then you would need to call `StructuredArguments.value(String fieldName, Object value)` and pass a `String` as the value parameter.  In this case, Jackson will escape the String value, so it is a valid JSON string value.  If I understand correctly, it is your desire to add the value as a JSON string field.  Therefore, you would need to convert the object to a string value prior to passing it to `StructuredArguments.value`

**Comment by bplies-IAS** [comment]
Turns out escaping isn't necessary afterall.  It is just that in the applications where it isn't working the JSON payload is too large for whatever limit.  Closing issue.
