### ISSUE TITLE
CWE - 117 Improper Output Neutralization

### ISSUE THREAD

**Issue by JakubJecminek** [logstash/logstash-logback-encoder#331]
Hi,
we are using logstash logback encoder and we ran into problem with veracode which reports CWE 117 issue https://cwe.mitre.org/data/definitions/117.html. Is net.logstash.logback.encoder.LogstashEncoder safe against this weakness? That would mean that this veracode report is false positive. Also, does anybody have experience with this issue in veracode?
Thank you,
Jakub

**Comment by philsttr** [comment]
The JSON encoders provided by logstash-logback-encoder use [Jackson](https://github.com/FasterXML/jackson) to write JSON output.

Jackson will ensure that output is valid JSON, unless _raw_ output is used.  For normal non-raw output (which is the most common scenario) Jackson will properly escape any control characters in log output.

Therefore, an application that uses logstash-logback-encoder will not be vulnerable to CWE-117 _if the application does not use raw output_.

An application _might_ be vulnerable to CWE-117 if the application writes raw output via:
* Usage of any of the following methods:
  * `Markers.appendRaw`
  * `StructuredArguments.raw`
  * `StructuredArguments.r`
* Defining a custom `JsonProvider` that appends raw output to the `JsonGenerator`

If the application writes raw JSON output, then it is up to the application to ensure that the raw values being written are properly escaped and well-formed JSON in order to avoid CWE-117

**Comment by JakubJecminek** [comment]
Thank you very much for thorough explanation.
