### ISSUE TITLE
Lazy / Supplier interfaces for Markers and StructuredArguments

### ISSUE THREAD

**Issue by wsargent** [logstash/logstash-logback-encoder#334]
I've run into a case where there are potentially some very large JSON documents that need to be serialized.

If I run `Markers.appendRaw(json.parse())` then parsing the JSON can take up to 100ms on the rendering thread.  I'd like there to be a lazy version of appendRaw (and the other methods, I suppose), so that I can do:

```java
Markers.appendDeferredRaw(fieldName, () -> json.parse())
```

and have the JSON rendered lazily.  It would be nice if it were memoized, but not needed as if it's not on the rendering thread it's just background CPU noise.

**Comment by philsttr** [comment]
Seems reasonable.

I'll need to bump the minimum java version to 1.8  (it's currently 1.7), which I was planning on doing for the next major version (6.0) anyway.

Also, I might be able to make a single `defer` method that took a `Supplier<LogstashMarker>`, so that I don't need to create deferred versions of every other method.

```java
Markers.defer(() -> Markers.appendRaw(fieldName, json.parse()))
```
