### ISSUE TITLE
Have public access to `connectedDestinationIndex`

### ISSUE THREAD

**Issue by brenuart** [logstash/logstash-logback-encoder#344]
I'm looking for an easy way to know to which destination the appender is currently connected.
This information is currently held in the `connectedDestinationIndex` private field.
Can we make this information publicly available ?

A side question is whether the appender is connected or offline. This can be deduced by implementing a `TcpAppenderListener` but it could be interesting for the appender to provide another easier approach.

**Comment by philsttr** [comment]
Rather than providing a simple getter to get the destination index, I think it would be best to provide a method that returned an `Optional<InetSocketAddress>` for the currently connected destination.

The reason for having a single method as opposed to two methods (one for index, and one for state) is that you really need to know the state to interpret the index.  And having two separate methods would introduce a race condition.

So, would this signature work for you?  (and do you have any other thoughts/recommendations?)

```
/**
 * Returns the currently connected destination as an Optional.
 * The Optional will be absent if the appender is not currently connected.
 */
Optional<InetSocketAddress> getConnectedDestination()
```

**Comment by brenuart** [comment]
Sounds good to me.
