### ISSUE TITLE
host is not refreshed after DNS cache refreshed 

### ISSUE THREAD

**Issue by uzcoorg** [logstash/logstash-logback-encoder#351]
Hi There,

Appender still holds old IP address of host.  When logstash-host comes up with new IP logging stops,  JVM refresh cached DNS every 60 seconds. Is there are way refresh the appender ? 

<appender name="STASH" class="net.logstash.logback.appender.LogstashSocketAppender">
        <host>logstash-host</host>
        <port>5514</port>
    </appender>

**Comment by philsttr** [comment]
The TCP appender will [re-resolve the hostname](https://github.com/logstash/logstash-logback-encoder/blob/5e4e8bef91266a7abfe398cde9d2bbc109658159/src/main/java/net/logstash/logback/appender/AbstractLogstashTcpSocketAppender.java#L582-L586) every time it reconnects to the destination.  The appender will reconnect when the existing connection is severed.

Can you enable `debug="true"` in your logback configuration xml, and provide the console output for when you encounter this situation?

When you encounter this situation, did the "old" logstash host shutdown (thus severing the existing connection)?

**Comment by uzcoorg** [comment]
Our app uses  UDP appender, after resolving host-ip it keeps publishing to that IP. When on AWS logstash host restarts host IP will change, appender does not re-resolve host, only way is restart java application. 
  <appender name="STASH" class="net.logstash.logback.appender.LogstashSocketAppender">
        <host>logstash-host</host>
        <port>5515</port>
        <customFields>{"app":"${stackname}", "component": "services"}</customFields>
        <throwableConverter class="net.logstash.logback.stacktrace.ShortenedThrowableConverter">
            <maxDepthPerThrowable>50</maxDepthPerThrowable>
            <shortenedClassNameLength>40</shortenedClassNameLength>
            <rootCauseFirst>true</rootCauseFirst>
            <inlineHash>true</inlineHash>
        </throwableConverter>
    </appender>

**Comment by uzcoorg** [comment]
``  <appender name="STASH" class="net.logstash.logback.appender.LogstashSocketAppender">
        <host>logstash-host</host>
        <port>5515</port>
        <customFields>{"app":"${stackname}", "component": "services"}</customFields>
        <throwableConverter class="net.logstash.logback.stacktrace.ShortenedThrowableConverter">
            <maxDepthPerThrowable>50</maxDepthPerThrowable>
            <shortenedClassNameLength>40</shortenedClassNameLength>
            <rootCauseFirst>true</rootCauseFirst>
            <inlineHash>true</inlineHash>
        </throwableConverter>
    </appender>``

**Comment by philsttr** [comment]
Unfortunately, this cannot be easily fixed in logstash-logback-encoder, since logstash-logback-encoder uses logback's UDP support via [`SyslogOutputStream`](https://github.com/qos-ch/logback/blob/master/logback-core/src/main/java/ch/qos/logback/core/net/SyslogOutputStream.java#L43)), which only resolves the address on startup.

We would need logback to add support for re-resolving the host in `SyslogOutputStream`.  Otherwise, logstash-logback-encoder would need to entirely rewrite UDP support without using logback's support (which I would like to avoid).

So, I would recommend filing an issue with logback for this support, after which logstash-logback-encoder can take advantage of it.  Also, I'm not entirely sure of a good strategy for _when_ to re-resolve the host.  It shouldn't be done on every event for performance reasons.  Perhaps it could be done on a timer or something.

**Comment by philsttr** [comment]
As an alternative, you could switch to the TCP appender, which re-resolves the host on reconnects
