### ISSUE TITLE
Switch from FastDateFormat for higher precision timestamps

### ISSUE THREAD

**Issue by kyrias** [logstash/logstash-logback-encoder#364]
Currently `logstash-logback-encoder` uses `FastDateFormat` to generate the timestamps, but it is limited to millisecond precision.  Java 8 added `java.time` which has nanosecond precision.  Since `logstash-logback-encoder >= 6` requires Java 8, would it be possible to switch to `java.time.Instant` for generating the timestamps instead?

**Comment by J-Jimmy** [comment]
Sorry, I don't know how to like PR's to Issues, but take a look at https://github.com/logstash/logstash-logback-encoder/pull/365

**Comment by kyrias** [comment]
Nice, though I don't have enough Java experience or knowledge of the code to be able to really review it.

Though I guess [LOGBACK-1374](https://jira.qos.ch/browse/LOGBACK-1374) would be necessary as well, since I hadn't noticed that the timestamp is gotten from `ILoggingEvent` which returns the timestamp in milliseconds.

**Comment by philsttr** [comment]
Thanks for the issue report @kyrias and PR @J-Jimmy !

I 100% agree with replacing `FastDateFormat` with `DateTimeFormatter`.  In addition to supporting higher precision timestamps, it has the added benefit of removing a dependency on commons-lang3.

As you mentioned @kyrias , higher-precision timestamps won't be supported until logback supports them, but we can go ahead and make the necessary changes in logstash-logback-encoder in preparation.

I've added some review comments on the PR that need to be addressed before I can merge the PR.

Also, this change will require a major version bump of logstash-logback-encoder.  So I might hold off on it for a bit.  There's no real immediate need for it since logback doesn't support higher-precision timestamps yet.

**Comment by philsttr** [comment]
Closing this in favor of #377
