### ISSUE TITLE
Is there a way to avoid duplicate fieldNames logging with StructuredArguments.keyValue?

### ISSUE THREAD

**Issue by blacksab** [logstash/logstash-logback-encoder#422]
We are using logstashLogbackEncoderVersion = '6.4'

Hi, 
we have a setup where we have some shared lib for logging insight.

The insight logger adds some default StructuredArguments.

```
SharedLogger logger;
logger.log("First", kv("key", "value"))
```
Which results in the following log statement:
```
{
...
  "shared": "one",
  "key": "value"
...
}
```

The issue arises when we try to log the following
```
logger.log("First", kv("shared", "two"))
```
Result
```
{
...
  "shared": "one",
  "shared": "two"
...
}
```

Is there a way to avoid such duplicates? We have tried to implement a fieldName-sanitizer, but the variety of Markers prevents us.

Another question is of course what filedValue to choose when duplicate fieldNames exists?

**Comment by philsttr** [comment]
#### Option 1

You can _prevent_ duplicate field names by enabling [`JsonGenerator.Feature.STRICT_DUPLICATE_DETECTION`](https://javadoc.io/doc/com.fasterxml.jackson.core/jackson-core/latest/com/fasterxml/jackson/core/JsonGenerator.Feature.html#STRICT_DUPLICATE_DETECTION).  However, this will cause an exception to be thrown when duplicates are detected, rather than selecting one of the fields.

```xml
<jsonGeneratorDecorator class="net.logstash.logback.decorate.FeatureJsonGeneratorDecorator">
  <enable>STRICT_DUPLICATE_DETECTION</enable>
</jsonGeneratorDecorator>
```

#### Option 2

You could theoretically implement a `JsonGenerator` that ignored duplicate field names by extending [`JsonGeneratorDelegate`](https://javadoc.io/doc/com.fasterxml.jackson.core/jackson-core/latest/com/fasterxml/jackson/core/util/JsonGeneratorDelegate.html), keeping track of field names written for each json object, and writing the field only if the field name has not been encountered previously. You can configure logstash-logback-encoder to use your implementation by using a JsonGeneratorDecorator.  See [here](https://github.com/logstash/logstash-logback-encoder#customizing-json-factory-and-generator).  This approach would select the _first_ field encountered, and ignore later duplicates. 

For help implementing this JsonGenerator, take a look at how Jackson implements the STRICT_DUPLICATE_DETECTION feature, and how the [`MaskingJsonGenerator`](https://github.com/logstash/logstash-logback-encoder/blob/master/src/main/java/net/logstash/logback/mask/MaskingJsonGenerator.java) handles delegation and filtering.

#### Option 3

Change your SharedLogger to not use Structured Arguments for the "shared" field.  Instead, implement your own [`JsonProvider`](https://github.com/logstash/logstash-logback-encoder/blob/master/src/main/java/net/logstash/logback/composite/JsonProvider.java) that obtains the value of "shared" from some other location (maybe a ThreadLocal?, maybe the MDC?), and writes the value obtained, or a default value.

This approach is only for _specific_ fields, and is not a general solution to avoid duplicates.

**Comment by blacksab** [comment]
Thanks, @philsttr.

We'll remove the method accepting StructuredArgument. Our shared logger will only accept map input. A concat. of the default map and the input map will ensure unique keys.
