### ISSUE TITLE
Provide a SequenceJsonProvider to help preserving order of events emitted during the same millisecond

### ISSUE THREAD

**Issue by brenuart** [logstash/logstash-logback-encoder#462]
Timestamps have a precision up to the millisecond, meaning that sorting events on the timestamp does not necessarily preserve the sequence and, depending on the sorting algorithm, we may end up with event 2 appearing before event 1.

To solve that issue we added a custom `SequenceJsonProvider` that outputs an additional `seq` field in the JSON output. That field is basically a counter that is reset every milliseconds (to keep the value small and optimise storage on the backend store). 

That strategy obviously depends on the configured timestamp format: if user opts for a format with a precision up to the second, the counter must be reset every second instead of milliseconds. An alternative is to use an ever-increasing counter... (but what would happen when it reaches the maximum and is reset to zero?)

I was wondering if other people would be interested in such feature and if it is worth to be included in the library...
What do you think ?

BTW: would it be possible to schedule a "live" chat together one of these days? I have other features and design issues I'd like to discuss with you. A chat can sometimes be easier that exchanging "emails" through the GitHub issues.

/Bertrand

**Comment by philsttr** [comment]
Hey Bertrand,

logstash-logback-encoder has a [SequenceJsonProvider](https://github.com/logstash/logstash-logback-encoder/blob/master/src/main/java/net/logstash/logback/composite/loggingevent/SequenceJsonProvider.java) that uses an increasing long counter, starting from 0.  Rollover is not a concern since if the application logs a message every _micro_ second, it will take close to 300 thousand years before it rolls over.

Email me at logstash dot logback dot encoder at gmail dot com, and we can set up a live chat.

**Comment by brenuart** [comment]
I missed that one... 
Rollover is indeed not an issue. Only the size of the sequence number may be an issue for some people... But I don't think it is worth to implement another solution. If the need arise, one can implement is own provider and/or file an issue.
If you agree, you can close the issue.
