### ISSUE TITLE
Remove @deprecated methods for v7.x

### ISSUE THREAD

**Issue by brenuart** [logstash/logstash-logback-encoder#470]
The next release is a MAJOR release (7.x) - it is probably time to remove some (all?) of the `@deprecated` methods and classes that have been kept around for backward compatibility.

**Comment by philsttr** [comment]
Removed all deprecated functionality except for `LogstashMarker.with`.  I'm going to leave that since it could be prevalent in business logic, making upgrades difficult.  The removed deprecated functionality was mainly isolated to logging configuration, which should only affect small portions of codebases.
