### ISSUE TITLE
Global custom fields with dynamic values

### ISSUE THREAD

**Issue by pawons** [logstash/logstash-logback-encoder#54]
Apologies if this is wrog place. I'm new here.
for instance, we have the following custom conversion 
<conversionRule conversionWord="uid" converterClass="com.mypkg.UserIdConverter" />
that captures user name.
<code>

<Pattern>%d{HH:mm:ss.SSS} {%uid} [Thread-%t] %-5level SQL - %msg%n</Pattern>
</code>
the resulting json log message does not capture %uid. I've tried using the customFields option but it outputs static value only.

Any advice?

Thanks,
Pavan

**Comment by philsttr** [comment]
Hi @pawons,

In the upcoming release (4.0, not released yet), there are now multiple ways of providing global custom fields with dynamic values.

Since you have already created and registered a Converter using a conversionRule, the easiest way to do so would be to use the new `LoggingEventPatternJsonProvider`.

For example, if you are using a `LogstashEncoder`, then you can add it like this:

```xml
<encoder class="net.logstash.logback.encoder.LogstashEncoder">
  <provider class="net.logstash.logback.composite.loggingevent.LoggingEventPatternJsonProvider">
    <pattern>
        {
          "uid": "%uid"
        }
    </pattern>
  </provider>
</encoder>
```

You could also implement your own `net.logstash.logback.composite.JsonProvider`, and add the provider (instead of the LoggingEventPatternJsonProvider).

Closing this issue now.
