### ISSUE TITLE
Remove deprecated LogstashMarker#with()

### ISSUE THREAD

**Issue by brenuart** [logstash/logstash-logback-encoder#615]
Time to remove the deprecated `LogstashMarker#with(Marker)` method before releasing version 7.0

**Comment by philsttr** [comment]
I'd prefer to not remove `with` in 7.0, since 6.6 documentation still references it (fixed in #463 in 7.0), and since it could be prevalent in app code (see https://github.com/logstash/logstash-logback-encoder/issues/470#issuecomment-868924723).  It's a pretty small method, so there's any maintenance overhead in keeping it around a bit longer.

**Comment by brenuart** [comment]
Ok - leave it for now. Closing issue with status "invalid".
