### ISSUE TITLE
Confusing docs

### ISSUE THREAD

**Issue by analytically** [logstash/logstash-logback-encoder#72]
I need to configure LogstashTcpSocketAppender with a LogstashEncoder? And how do I use LoggingEventAsyncDisruptorAppender? It's not clear in the readme.

**Comment by philsttr** [comment]
Hi @analytically ,

The [readme|https://github.com/logstash/logstash-logback-encoder#tcp-appenders] gives an example of how to use LogstashTcpSocketAppender with a LogstashEncoder.

I'll copy it here:

```xml
<configuration>
  <appender name="stash" class="net.logstash.logback.appender.LogstashTcpSocketAppender">
      <!-- remoteHost and port are optional (default values shown) -->
      <remoteHost>127.0.0.1</remoteHost>
      <port>4560</port>

      <!-- encoder is required -->
      <encoder class="net.logstash.logback.encoder.LogstashEncoder" />
  </appender>
```

Also, as mentioned a little lower in the readme, the `LogstashTcpSocketAppender` is itself asynchronous, so there's not need to wrap it in another async appender (such as `LoggingEventAsyncDisruptorAppender`).

The `LoggingEventAsyncDisruptorAppender` is really just provided as a substitute for logback's own `AsyncAppender`.  The `LoggingEventAsyncDisruptorAppender` will delegate to another appender the same way logback's `AsyncAppender` does.  The advantage of using `LoggingEventAsyncDisruptorAppender` over `AsyncAppender` is that a RingBuffer is used as the data structure to transfer events between threads (as opposed to a BlockingQueue).  The `LoggingEventAsyncDisruptorAppender` will never block the logging thread (unlike `AsyncAppender`).

Let me know if you have other specific questions.

**Comment by philsttr** [comment]
I just pushed an update to the readme to clarify the following in the readme:

* output configuration for the UDP appender is configured at the appender level.
* output configuration for the TCP appender (and other appenders) is configured at the encoder level.

I realize it's a little confusing.  I'd like to make the UDP appender be configured just like the TCP appender (and most every other logback appender).  Meaning, you would have to configure a layout/encoder within the appender.  However, I can't change it due to backwards compatibility issues.

I'm going to close this issue.  If you have other specific questions, feel free to ask (on this issue, or another one).  I'll respond.
