### ISSUE TITLE
Disruptor wait strategy causing high CPU load

### ISSUE THREAD

**Issue by MikeN123** [logstash/logstash-logback-encoder#75]
Since the logstash encoder uses a disruptor/ringbuffer for performance reasons, it constantly uses 20% CPU on our systems. Reason for this is the `SleepingWaitStrategy` which is used by the disruptor (Yourkit sample of 34 secs shows 9 sec in the disruptor, this is wall time I think, but the parkNanos(1) call is not really the greatest option on high resolution systems, and our application was doing nothing else) :

![screen shot 2015-02-08 at 12 31 10](https://cloud.githubusercontent.com/assets/940409/6096382/75c4f074-af8e-11e4-9854-45ddef165256.png)

See http://grokbase.com/t/gg/graylog2/12bw0tv8vq/disruptor-and-cpu-usage for the same issue in graylog2.

I see the `WaitStrategy ` can be set in `AsyncDisruptorAppender`, but this is probably not easily done from the logback config (is it?), and I am wondering if the default wait strategy shouldn't be different.

**Comment by philsttr** [comment]
Hi Mike,

You can set the wait strategy via logback xml config.  But doing so is not as intuitive as it could be because the disruptor classes are shaded within the logstash-logback-encoder jar.  Here's an example:

```xml
<appender name="stash" class="net.logstash.logback.appender.LogstashTcpSocketAppender">
      <!-- remoteHost and port are optional (default values shown) -->
      <remoteHost>127.0.0.1</remoteHost>
      <waitStrategy class="net.logstash.logback.encoder.com.lmax.disruptor.BlockingWaitStrategy"/>
      <encoder class="net.logstash.logback.encoder.LogstashEncoder" />
  </appender>
```

For the next release, I will:

* change the default to be `BlockingWaitStrategy` to be CPU conservative.
* make it more intuitive about how to change the wait strategy (by providing a simple string value)
* add a note in the documentation about how to change it

**Comment by MikeN123** [comment]
Ah, great, thanks for the response. Didn't know you could set the wait strategy like that, thanks.

**Comment by philsttr** [comment]
The changes I mentioned in my previous comment have been made for 4.1 (not released yet).

See the new [readme](https://github.com/logstash/logstash-logback-encoder#async)

**Comment by MikeN123** [comment]
Awesome, thanks for the fast follow-up!
