### ISSUE TITLE
Pattern to replace sensitive information in the message

### ISSUE THREAD

**Issue by kamaltherocky** [logstash/logstash-logback-encoder#79]
Hi,

I want to replace the sensitive information in the log using the layout pattern replace method. while i was using the rollingappender, i was able to use the pattern with %replace to do the same.

<layout class="ch.qos.logback.classic.PatternLayout">
			<Pattern>%d{HH:mm:ss.SSS} [%X{IPAddress}] [%thread] %-5level
				%logger{36} - %replace(%msg){'"sensitive":"[\w\s\S]+?"',
				'"sensitive":"**********"'}%n
			</Pattern>
		</layout>

Now i am using the net.logstash.logback.encoder.LogstashEncoder and not sure how to do the same. When i look at the json , the sensitive information is clearly visible.

please advise.

Regards
Kamal

**Comment by philsttr** [comment]
Hi Kamal,

The best way to do this would be to use a [composite encoder](https://github.com/logstash/logstash-logback-encoder#composite_encoder) with a [pattern provider](https://github.com/logstash/logstash-logback-encoder#provider_pattern), instead of a `LogstashEncoder` 

For example:

```xml
<encoder class="net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder">
  <providers>
    <timestamp/>
    <pattern>
      <pattern>
        {
          "message": "%replace(%msg){'sensitive','**********'}"
        }
      </pattern>
    </pattern>
  </providers>
</encoder>
```

Add other providers as needed.


You can also use the pattern provider with the `LogstashEncoder`, but it's a bit of a hack. 

For example:

```xml
<encoder class="net.logstash.logback.encoder.LogstashEncoder">
  <fieldNames>
    <!-- Do not output the standard message field.  It will be output by the pattern provider below -->
    <message>[ignore]</message>
  </fieldNames>
  <!-- Output the message field with sensitive values replaced -->
  <provider class="net.logstash.logback.composite.loggingevent.LoggingEventPatternJsonProvider">
    <pattern>
        {
          "message": "%replace(%msg){'sensitive','**********'}"
        }
    </pattern>
  </provider>
</encoder>
```

**Comment by raquibmahmood** [comment]
Hi,

Is it possible to replace a string in request content or response content? 
As I am getting backslash in json request and response.

Regards
Shoeb

**Comment by pa198924** [comment]
Is there any way to do replace by mapping the values of the POJO classes field name?

**Comment by philsttr** [comment]
logstash-logback-encoder does not have first-class support for masking sensitive data.

However, you can accomplish masking by customizing how Jackson performs serialization, and then [configure logstash-logback-encoder to use your customized JsonFactory / JsonGenerator from jackson](https://github.com/logstash/logstash-logback-encoder#customizing-json-factory-and-generator).

For example, [here is one way to perform masking within Jackson](https://stackoverflow.com/a/42122479/11248746).
You can modify that example to look for specific field names instead of an annotation.

Alternatively, you could implement a [JsonGeneratorDelegate](https://github.com/FasterXML/jackson-core/blob/master/src/main/java/com/fasterxml/jackson/core/util/JsonGeneratorDelegate.java) subclass that performs masking before delegating.
