### ISSUE TITLE
Documentation required for configuration (events lost)

### ISSUE THREAD

**Issue by fvisticot** [logstash/logstash-logback-encoder#97]
I'm using the following configuration to send 4 000 000 events to logback.
A lot of events are losts.

Can you please provide some documentation to help understand the required configuration to not loose events ?

<appender name="LOGSTASH" class="net.logstash.logback.appender.LogstashTcpSocketAppender">
    	<remoteHost>XXXX</remoteHost>
    	<port>9292</port>
    	<keepAliveDuration>5 minutes</keepAliveDuration>
    	<encoder class="net.logstash.logback.encoder.LogstashEncoder" />
	</appender>

**Comment by philsttr** [comment]
Hi @fvisticot

The TCP appender (`LogstashTcpSocketAppender`) is currently designed to never block the logging thread in your application.  It assumes the work being performed by the application is more important than the logs that the application generates, so it prioritizes application performance over log reliability.

If the RingBuffer is full (e.g. due to slow network, etc), then events will be dropped.  Therefore, you'll need to ensure the network and destination can keep up with your logging rate.

The TCP appender reports when it drops messages to logback's status listener.  You can add a status listener to see these messages like this:

```
<statusListener class="ch.qos.logback.core.status.OnConsoleStatusListener" />
```

The UDP appender (`LogstashSocketAppender`) uses UDP, which does not have guaranteed delivery, so there's no way for the appender to guarantee log delivery.


If you want guaranteed delivery of all log events, then I would recommend synchronously writing out to disk (you can use logback's `RollingFileAppender`), and then having a separate agent (e.g. logstash-forwarder) forward those files to your logstash destination.

**Comment by philsttr** [comment]
One other thing to consider.  In order to guarantee that logged messages have had a chance to be processed by asynchronous appenders (including the TCP appender), you'll need to [cleanly shut down logback](http://logback.qos.ch/manual/configuration.html#stopContext) when your application exits.

**Comment by philsttr** [comment]
I added a note about cleanly shutting down logback to the README.md

**Comment by InternetPseudonym** [comment]
> The UDP appender (`LogstashSocketAppender`) uses UDP, which does not have guaranteed delivery, so there's no way for the appender to guarantee log delivery.

I think it should be noted that this assumption is nonsensical. If the L3 protocol does not guarantee delivery one will have to implement message-acknowledgement, preferrably including message hashes. TCP already does that, of course _(including quite a few other things)_. Its rather trivial to generate ACK packets and wait for them on the other side - reliably handling the ACK queue and RESEND mechanisms, though ... can be challenging and requires actual software development experience. Thats why everyone always should choose TCP over UDP, there are rare exceptions like gaming networks and/or multicast.

**Comment by philsttr** [comment]
Updated the comment
