### ISSUE TITLE
How to ignore default fields

### ISSUE THREAD

**Issue by martinhynar** [logstash/logstash-logback-encoder#98]
Hi,

could you please document, how default fields could be ignored? For me, there is no use for these default fields: logger_name, thread_name, level, level_value, HOSTNAME and I want to get rid of them.
The single-word names are ignored by just `<level>[ignore]</level>` (as documented) but the two-word names are not so obvious. By little experimenting, I found almost all keys
`logger_name = logger, thread_name = thread, level_value = levelValue`
but I am not able to find out correct key for `HOSTNAME`.

**Comment by philsttr** [comment]
Hi @martinhynar 

The [documentation](https://github.com/logstash/logstash-logback-encoder/blob/master/README.md#custom_field_names) mentions looking at  [`LogstashFieldNames`](https://github.com/logstash/logstash-logback-encoder/blob/master/src/main/java/net/logstash/logback/fieldnames/LogstashFieldNames.java#L27) to determine the field names that can be customized.  Each field in that class is the name of a field that can be customized.  I'll try to make this more clear.

The `HOSTNAME` field actually comes from a property in the logback context.  It can be removed by setting `<includeContext>false</includeContext>`.


Alternatively, since you are removing a lot of the standard field names, I would recommend using the [composite encoder](https://github.com/logstash/logstash-logback-encoder/blob/master/README.md#composite-encoderlayout) instead of the `LogstashEncoder`.  The composite encoder lets you more easily select which fields you want included.

**Comment by martinhynar** [comment]
Great, thanks for explanation. The addition to documentation is also clear about that now.

**Comment by jama707** [comment]
I'm also trying to ignore those fields but it is not ignoring.
I debugged into encoder's source - it is correctly parsing xml `false` value and it is removing `mdcProvider` and setting it to null at `LogstashFormatter#setIncludeMdc`
But it is still logging MDC details.
My config is pretty simple:
   ```
 <appender name="JSON_LOG" class="ch.qos.logback.core.rolling.RollingFileAppender">
        <encoder class="net.logstash.logback.encoder.LogstashEncoder">
            <includeMdc>false</includeMdc>
        </encoder>
   </appender>
```
I'm not sure what I'm doing wrong here.

**Comment by philsttr** [comment]
Hi @jama707,
What fields are you trying to remove? HOSTNAME?

If so, use, `<includeContext>false</includeContext>`, not `<includeMdc>`

**Comment by jama707** [comment]
Hi @philsttr, I'm trying to remove `logger_name, version, thread_name, level, level_value, logs.home`

**Comment by philsttr** [comment]
`logger_name, version, thread_name, level, level_value` are not in the MDC.

To disable those, you'll need to set their field names to `[ignore]` as mentioned [here](https://github.com/logstash/logstash-logback-encoder#custom_field_names)

I've never seen `logs.home` before, so I'm not sure where that is coming from.

However, if you are removing all the default fields, I would suggest using the [composite encoder](https://github.com/logstash/logstash-logback-encoder/blob/master/README.md#composite-encoderlayout) instead of the `LogstashEncoder`.  The composite encoders allow you to selectively add things as needed (rather than removing things).

**Comment by jama707** [comment]
Finally figured out! Initially it didnt work for the fields which has underscore. Because ignore check field names are not the same as json - it should be the same as defined in `LogstashFieldNames`. It was only ignoring version/level which is the same name as in json and setter. 
I think consistency should be kept in naming the fields or we need to add some documentation on this.

Thanks a lot @philsttr!!

**Comment by jonvargas** [comment]
Thanks jama707, your last reply was pretty helpful, and yes, there should be consistency. Now, this works:

`        <encoder class="net.logstash.logback.encoder.LogstashEncoder">
            <includeContext>false</includeContext>
            <includeCallerData>true</includeCallerData>
            <fieldNames>
                <timestamp>timestamp</timestamp>
                <message>message</message>
                <thread>[ignore]</thread>
                <logger>[ignore]</logger>
                <version>[ignore]</version>
                <levelValue>[ignore]</levelValue>
                <caller>trace</caller>
                <stackTrace>exception</stackTrace>
                <mdc>context</mdc>
            </fieldNames>
        </encoder>
`

**Comment by KiraResari** [comment]
@jonvargas : Six years later, your response still saved my tail! This was the first mention I found anywhere that you can explicitly ignore fields by calling them "[ignore]", and it works like a charm!
